/* Ankle, foot & balance — catalogue moves. Data only; see coach/catalog.js and docs/EXERCISE-LIBRARY.md. */
(function (root) {
  'use strict';
  const C = (typeof module !== 'undefined' && module.exports) ? require('../catalog.js') : root.FyzioCatalog;
  const KNEE = { kind: 'angle', pts: ['HIP', 'KNEE', 'ANK'] };
  const ANKLE = { kind: 'angle', pts: ['KNEE', 'ANK', 'FOOT'] };
  const TRUNK = { kind: 'tilt', pts: ['SH', 'HIP'] };
  const LEAN = { kind: 'lean', pts: [] }, PELVIS = { kind: 'pelvis', pts: [] };
  const balanceHold = [{ metric: LEAN, rel: 'change', min: -8, max: 8 }, { metric: PELVIS, rel: 'change', min: -6, max: 6 }];

  C.defineCatalog({
    region: 'ankle', group: 'Ankle, foot & balance', order: 1300,
    camera: { height: 'knee', distance: '2 m', posture: 'standing' },
    sources: [
      { name: 'Cleveland Clinic — ankle strengthening exercises', url: 'https://health.clevelandclinic.org/ankle-exercises-weak-ankles' },
      { name: 'Achilles Foot & Ankle Center — ankle injury rehabilitation exercises', url: 'https://achillesfootandankle.com/ankle-injury-rehabilitation-exercises/' },
      { name: 'Evolve NY — foot and ankle strengthening', url: 'https://evolveny.com/blogposts/exercises-to-strengthen-feet-and-ankles' },
    ],
  }, [
    {
      id: 'calf_raise', name: 'Calf raise (both legs)', type: 'reps', view: 'side', tracking: 'form', level: 'beginner', equipment: ['wall for balance'],
      muscles: { primary: ['gastrocnemius', 'soleus'], secondary: ['foot intrinsics'] },
      summary: 'Rise onto the balls of both feet, pause at the top, lower slowly with the knees straight.',
      setup: 'Stand side-on to the phone, fingertips on a wall, feet hip-width. Push up onto the balls of the feet as high as you can, pause, then lower over three seconds.',
      why: 'From the side the ankle angle opens as the heel rises, which counts the reps, and a knee bending to help is visible as the hip–knee–ankle angle dropping.',
      progress: { metric: ANKLE, start: 'calibrated', target: 25, targetIsDelta: true },
      tempo: 'Up 2 s, hold 1 s, down 3 s.', dosage: '3 × 15.', progression: 'Single leg; heels off a step for extra range.', regression: 'Seated calf raise; smaller rise.',
      contraindications: 'Achilles pain that worsens through the set.',
      faults: [
        { id: 'kneebend', label: 'Knees bending to help', cue: 'Knees straight', tip: 'Lock the knees so the calf does the lifting; bent knees shift the work and shorten the range.', severity: 2, metric: KNEE, op: '<', threshold: 165, minP: 0.2, persist: 300 },
        { id: 'roll', label: 'Rolling onto the outside of the feet', cue: 'Big toe down', tip: 'Press through the big toe joint at the top so the ankle rises straight rather than rolling out.', severity: 2 },
      ],
      guide: { surface: 'Firm floor; a wall or rail in front.', stop: 'Achilles or arch pain that builds.', cannotSee: 'The foot rolling outward — that is a front-view detail.',
        regions: [{ name: 'Ankles', points: [{ t: 'Rise as high as possible; lower slowly.', tracked: true }, { t: 'Weight over the big toe at the top.', tracked: false }] }, { name: 'Knees', points: [{ t: 'Straight throughout.', tracked: true }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 0, shin: 0, foot: 0, uarm: 60, farm: 60 }, B: { face: 'right', torso: 0, thigh: 0, shin: 0, foot: -35, uarm: 60, farm: 60 }, work: { calf: 1 }, wall: 'ahead' },
    },
    {
      id: 'single_calf_raise', name: 'Single-leg calf raise', type: 'reps', view: 'side', tracking: 'form', level: 'intermediate', equipment: ['wall for balance', 'step (optional)'],
      muscles: { primary: ['gastrocnemius', 'soleus'], secondary: ['peroneals', 'foot intrinsics'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'A calf raise on one leg — the standard for Achilles and ankle rehab.',
      setup: 'Stand on one leg side-on to the phone, working leg nearest, fingertips on a wall. Rise onto the ball of the foot, pause, lower over three seconds. Keep the knee straight and the ankle from rolling out.',
      why: 'The ankle angle counts each rise from the side; the knee bending shows as the leg angle closing.',
      progress: { metric: ANKLE, start: 'calibrated', target: 25, targetIsDelta: true },
      tempo: 'Up 2 s, hold 1 s, down 3 s.', dosage: '3 × 10–15 each leg.', progression: 'Heel off a step; hold a weight.', regression: 'Two-leg calf raise.',
      contraindications: 'Achilles pain above a mild ache.',
      faults: [
        { id: 'kneebend', label: 'Knee bending to help', cue: 'Knee straight', tip: 'Keep the knee locked; the rise comes from the ankle alone.', severity: 2, metric: KNEE, op: '<', threshold: 165, minP: 0.2, persist: 300 },
        { id: 'roll', label: 'Ankle rolling outward', cue: 'Big toe down', tip: 'Drive through the big toe joint so the heel rises straight up.', severity: 3 },
      ],
      guide: { surface: 'Firm floor and a wall.', stop: 'Achilles pain, or the ankle rolling painfully.', cannotSee: 'The ankle rolling outward.',
        regions: [{ name: 'Working ankle', points: [{ t: 'Full rise, slow lower, heel tracking straight up.', tracked: true }] }, { name: 'Knee', points: [{ t: 'Straight and still.', tracked: true }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 0, shin: 0, foot: 0, thighF: 10, shinF: -60, uarm: 60, farm: 60 }, B: { face: 'right', torso: 0, thigh: 0, shin: 0, foot: -35, thighF: 10, shinF: -60, uarm: 60, farm: 60 }, work: { calf: 1 }, wall: 'ahead' },
    },
    {
      id: 'tibialis_raise', name: 'Tibialis raise', type: 'reps', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['wall'],
      muscles: { primary: ['tibialis anterior'], secondary: [] },
      summary: 'Back against a wall, feet a step out, lift the toes and forefoot off the floor with the heels down.',
      setup: 'Lean your back on a wall with the feet 30–40 cm in front of it, side-on to the phone. Keeping the heels down, lift the toes and balls of both feet as high as you can, then lower.',
      why: 'The ankle angle closing as the toes rise counts each rep from the side. The movement is small, so only the count is trusted.',
      progress: { metric: ANKLE, start: 'calibrated', target: -20, targetIsDelta: true },
      tempo: 'Up 1 s, hold 1 s, down 2 s.', dosage: '3 × 15–20.', progression: 'Feet further from the wall; single leg.', regression: 'Seated toe lifts.',
      contraindications: 'Shin pain that persists after the set.',
      faults: [ { id: 'heels', label: 'Heels lifting', cue: 'Heels planted', tip: 'The heels stay down; if they lift you are rocking, not lifting the toes.', severity: 2 }, { id: 'bounce', label: 'Bouncing the reps', cue: 'Pause at the top', tip: 'Hold the toes up for a second on every rep.', severity: 1 } ],
      guide: { surface: 'A wall and a floor with grip.', stop: 'Sharp shin pain.', cannotSee: 'Whether the heels stay fully planted.',
        regions: [{ name: 'Feet', points: [{ t: 'Toes and forefoot lift; heels stay down.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Back resting on the wall, body straight.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: -8, thigh: 12, shin: 0, foot: 0, uarm: 8, farm: 8 }, B: { face: 'right', torso: -8, thigh: 12, shin: 0, foot: 28, uarm: 8, farm: 8 }, work: { calf: .3 }, wall: 'behind' },
    },
    {
      id: 'ankle_alphabet', name: 'Ankle alphabet', type: 'reps', view: 'side', tracking: 'none', level: 'beginner', equipment: ['none'],
      muscles: { primary: ['ankle stabilisers'], secondary: ['tibialis anterior', 'peroneals'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Sitting with the leg supported, draw the letters of the alphabet in the air with the big toe.',
      setup: 'Sit with the leg out and the foot clear of the floor. Move only the ankle and draw each letter A to Z as large as the ankle allows.',
      why: 'The foot traces small shapes in every direction; a single camera cannot follow them. Follow the guide and log the set.',
      camera: { height: 'floor', distance: '1.5 m', posture: 'sitting' }, targets: [1, 2, 3], defaultTarget: 1,
      tempo: 'Slow and large.', dosage: '1–2 alphabets, 2–3 times a day.', progression: 'Capital letters, then lower case.', regression: 'Fewer letters.',
      contraindications: 'Sharp ankle pain in any direction — stop and note which.',
      faults: [ { id: 'knee', label: 'Moving the knee instead of the ankle', cue: 'Ankle only', tip: 'Rest the thigh so the shin stays still; the ankle draws the letters.', severity: 2 }, { id: 'small', label: 'Letters too small', cue: 'Draw them big', tip: 'Reach the end of the range in every direction; the point is motion, not speed.', severity: 1 } ],
      guide: { surface: 'A chair or the floor with the leg supported.', stop: 'Sharp pain in any direction.', cannotSee: 'Any of it — the foot moves in all directions at once.',
        regions: [{ name: 'Ankle', points: [{ t: 'Draws each letter to the end of the range.', tracked: false }] }, { name: 'Knee and hip', points: [{ t: 'Still — supported by the chair.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 90, shin: 60, foot: 0, uarm: 20, farm: 40 }, B: { face: 'right', torso: 0, thigh: 90, shin: 60, foot: 30, uarm: 20, farm: 40 }, work: { calf: .5 } },
    },
    {
      id: 'towel_curl', name: 'Towel curl', type: 'reps', view: 'side', tracking: 'none', level: 'beginner', equipment: ['towel', 'chair'],
      muscles: { primary: ['foot intrinsics'], secondary: ['toe flexors'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Sitting, scrunch a towel toward you with the toes, heel staying on the floor.',
      setup: 'Sit with a towel flat on the floor under the foot. Keeping the heel down, curl the toes to draw the towel toward you, release, repeat until it is bunched up.',
      why: 'The toes move a few millimetres under a towel; there is nothing a phone can count. Follow the guide and log the set.',
      camera: { height: 'floor', distance: '1.5 m', posture: 'sitting' }, targets: [1, 2, 3], defaultTarget: 2,
      tempo: 'Slow scrunches.', dosage: '2–3 towel lengths, daily.', progression: 'A small weight on the far end of the towel.', regression: 'Shorter towel.',
      contraindications: 'Cramp in the arch that does not ease.',
      faults: [ { id: 'heel', label: 'Heel lifting', cue: 'Heel down', tip: 'The heel stays planted so the toes, not the ankle, pull the towel.', severity: 2 }, { id: 'claw', label: 'Clawing with the tips of the toes', cue: 'Flat toes, spread', tip: 'Spread the toes and pull with the whole pad, not the tips.', severity: 1 } ],
      guide: { surface: 'Smooth floor so the towel slides.', stop: 'Arch cramp that does not settle.', cannotSee: 'Any of it.',
        regions: [{ name: 'Foot', points: [{ t: 'Heel planted; toes spread and pull the towel.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 90, shin: 0, foot: 0, uarm: 20, farm: 40 }, B: { face: 'right', torso: 0, thigh: 90, shin: 0, foot: 6, uarm: 20, farm: 40 }, work: { calf: .3 } },
    },
    {
      id: 'banded_dorsiflexion', name: 'Banded dorsiflexion', type: 'reps', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['resistance band', 'anchor point'],
      muscles: { primary: ['tibialis anterior'], secondary: [] }, sided: { limb: 'leg', by: 'camera' }, band: 'red',
      summary: 'Band around the top of the foot anchored in front; pull the toes up toward the shin.',
      setup: 'Sit on the floor with the leg out, side-on to the phone, band looped over the top of the foot and anchored ahead of you. Pull the toes toward you against the band, pause, release slowly.',
      why: 'The ankle angle closing as the toes pull up counts each rep from the side; the range is small, so only the count is trusted.',
      camera: { height: 'floor', distance: '2 m', posture: 'sitting' },
      progress: { metric: ANKLE, start: 'calibrated', target: -20, targetIsDelta: true },
      tempo: 'Pull 1 s, hold 1 s, release 2 s.', dosage: '3 × 15 each side.', progression: 'Heavier band.', regression: 'Lighter band, or no band.',
      contraindications: 'Shin pain that persists.',
      faults: [ { id: 'knee', label: 'Bending the knee to help', cue: 'Leg straight', tip: 'Keep the knee straight so the shin muscle does the pulling.', severity: 2 }, { id: 'snap', label: 'Letting the band snap back', cue: 'Release slowly', tip: 'The return is half the work — two seconds out.', severity: 1 } ],
      guide: { surface: 'Floor; the anchor must not move.', stop: 'Sharp shin or ankle pain.', cannotSee: 'The foot turning in or out as it pulls.',
        regions: [{ name: 'Ankle', points: [{ t: 'Toes pull straight toward the shin against the band.', tracked: true }] }, { name: 'Knee', points: [{ t: 'Straight, thigh resting.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 90, shin: 90, foot: 90, uarm: 30, farm: 90 }, B: { face: 'right', torso: 0, thigh: 90, shin: 90, foot: 120, uarm: 30, farm: 90 }, work: { calf: .4 } },
    },
    {
      id: 'banded_eversion', name: 'Banded eversion & inversion', type: 'reps', view: 'front', tracking: 'none', level: 'beginner', equipment: ['resistance band'],
      muscles: { primary: ['peroneals', 'tibialis posterior'], secondary: [] }, sided: { limb: 'leg', by: 'pick' }, band: 'red',
      summary: 'Sitting, turn the sole of the foot outward then inward against a band.',
      setup: 'Sit with the legs out, band looped around the forefoot and anchored to the side. Keeping the knee still, turn the sole outward against the band (eversion), release; then re-anchor the other way and turn it inward (inversion).',
      why: 'The foot rotates about the shin — a movement a phone sees as almost nothing from any angle. Follow the guide and log each direction.',
      camera: { height: 'floor', distance: '1.5 m', posture: 'sitting' }, targets: [10, 12, 15, 20], defaultTarget: 15,
      tempo: 'Turn 1 s, hold 1 s, return 2 s.', dosage: '3 × 15 each direction.', progression: 'Heavier band.', regression: 'No band — just the movement.',
      contraindications: 'Pain on the outside of the ankle after a sprain that has not been assessed.',
      faults: [ { id: 'knee', label: 'Rotating the whole leg', cue: 'Knee still', tip: 'Hold the shin with a hand if needed; only the foot turns.', severity: 2 }, { id: 'range', label: 'Tiny movements', cue: 'Full turn', tip: 'Take the sole as far out (or in) as it goes each rep.', severity: 1 } ],
      guide: { surface: 'Floor or a chair; band anchored to a table leg.', stop: 'Sharp pain on the outside or inside of the ankle.', cannotSee: 'The foot turning — the movement is a rotation the phone cannot resolve.',
        regions: [{ name: 'Foot', points: [{ t: 'Turns fully against the band; knee and shin stay still.', tracked: false }] }] },
      pose: { A: { legL: 6, legR: 6, armL: 20, armR: 20, foreL: 70, foreR: 70 }, B: { legL: 6, legR: 10, armL: 20, armR: 20, foreL: 70, foreR: 70 }, work: { calf: .5 } },
    },
    {
      id: 'single_leg_balance', name: 'Single-leg balance', type: 'hold', view: 'front', tracking: 'reps', level: 'beginner', equipment: ['none', 'cushion for progression'],
      muscles: { primary: ['ankle stabilisers', 'gluteus medius'], secondary: ['foot intrinsics', 'core'] }, sided: { limb: 'leg', by: 'pick' },
      summary: 'Stand on one leg, hips level, and hold still.',
      setup: 'Face the phone, lift one foot a few centimetres, soft standing knee, hands free. Keep the hips level and the trunk still. Hold.',
      why: 'Facing the phone shows the trunk swaying and the pelvis dropping, so the timer runs only while you are steady. Whether the other foot is really off the floor is not checked.',
      camera: { height: 'hip', distance: '2.5 m', posture: 'standing' }, targets: [15, 20, 30, 45, 60], defaultTarget: 30,
      hold: { conditions: balanceHold },
      tempo: 'Still, breathing normally.', dosage: '3 × 30 s each leg.', progression: 'Eyes closed; stand on a cushion; turn the head side to side.', regression: 'Fingertip on a wall; shorter holds.',
      contraindications: 'Dizziness; falls risk without something to hold.',
      faults: [ { id: 'hipdrop', label: 'Free-side hip dropping', cue: 'Hips level', tip: 'Lift the free hip slightly; the standing hip muscles hold the pelvis level.', severity: 3 }, { id: 'lock', label: 'Locking the standing knee', cue: 'Soft knee', tip: 'A slightly bent knee lets the ankle and hip do the balancing.', severity: 1 } ],
      guide: { surface: 'Firm floor; a wall within reach.', stop: 'Dizziness or a near fall.', cannotSee: 'Whether the lifted foot is really off the floor.',
        regions: [{ name: 'Pelvis', points: [{ t: 'Level throughout the hold.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Upright and still; no swaying.', tracked: true }] }, { name: 'Standing leg', points: [{ t: 'Soft knee, foot gripping the floor.', tracked: false }] }] },
      pose: { A: { legL: 0, legR: 0, armL: 15, armR: 15 }, B: { legL: 24, shinL: 10, legR: 2, armL: 35, armR: 35 }, work: { calf: .6, glute: .8, abs: .4 } },
    },
    {
      id: 'tandem_stance', name: 'Tandem stance', type: 'hold', view: 'front', tracking: 'reps', level: 'beginner', equipment: ['none'],
      muscles: { primary: ['ankle stabilisers'], secondary: ['gluteus medius', 'core'] },
      summary: 'Heel to toe on a line, hold still without stepping.',
      setup: 'Face the phone and place one foot directly in front of the other, heel touching toes. Hands free, look ahead. Hold, then swap feet.',
      why: 'Facing the phone shows the trunk swaying and the pelvis tilting, so the timer runs only while you are steady.',
      camera: { height: 'hip', distance: '2.5 m', posture: 'standing' }, targets: [15, 20, 30, 45, 60], defaultTarget: 30,
      hold: { conditions: balanceHold },
      tempo: 'Still, breathing normally.', dosage: '3 × 30 s each foot in front.', progression: 'Eyes closed; walk heel to toe along a line.', regression: 'Feet slightly apart; fingertip on a wall.',
      contraindications: 'Dizziness; falls risk.',
      faults: [ { id: 'arms', label: 'Waving the arms', cue: 'Arms quiet', tip: 'Use the ankles and hips to balance; keep the hands relaxed at the sides.', severity: 1 }, { id: 'step', label: 'Stepping out', cue: 'Reset and hold', tip: 'If you step, restart the hold — do not count the time before it.', severity: 2 } ],
      guide: { surface: 'Firm floor, a line on it if possible.', stop: 'Dizziness or a near fall.', cannotSee: 'Whether the heel really touches the toes.',
        regions: [{ name: 'Feet', points: [{ t: 'Heel to toe on one line.', tracked: false }] }, { name: 'Trunk', points: [{ t: 'Still and upright.', tracked: true }] }] },
      pose: { A: { legL: 0, legR: 0, armL: 12, armR: 12 }, B: { legL: 1, legR: 1, armL: 14, armR: 14 }, work: { calf: .7, abs: .3 } },
    },
    {
      id: 'heel_toe_walk', name: 'Heel walk & toe walk', type: 'reps', view: 'front', tracking: 'none', level: 'beginner', equipment: ['none'],
      muscles: { primary: ['tibialis anterior', 'calves'], secondary: ['ankle stabilisers'] },
      summary: 'Walk a few metres on the heels with toes lifted, then back on the toes with heels lifted.',
      setup: 'Walk 5–10 m on the heels, toes pulled up, then return on the balls of the feet, heels high. Small steps, tall posture.',
      why: 'Walking toward and away from the phone changes the framing every step; the count and the foot position are not measurable. Follow the guide and log the set.',
      targets: [2, 4, 6], defaultTarget: 4,
      tempo: 'Small, slow steps.', dosage: '2–4 lengths each way.', progression: 'Longer distance; carry a light weight.', regression: 'Shorter distance; hand on a wall.',
      contraindications: 'Shin or Achilles pain that builds.',
      faults: [ { id: 'drop', label: 'Toes or heels dropping mid-way', cue: 'Keep them up', tip: 'Shorten the walk before the foot drops; the position is the exercise.', severity: 2 }, { id: 'lean', label: 'Leaning to keep balance', cue: 'Stand tall', tip: 'Eyes ahead, trunk upright; use small steps rather than leaning.', severity: 1 } ],
      guide: { surface: 'A clear hallway.', stop: 'Shin or Achilles pain.', cannotSee: 'Any of it — the distance to the phone changes every step.',
        regions: [{ name: 'Feet', points: [{ t: 'Toes up on the heel walk; heels high on the toe walk.', tracked: false }] }] },
      pose: { A: { legL: 4, legR: 4, armL: 15, armR: 15 }, B: { legL: 6, legR: 6, armL: 20, armR: 20 }, work: { calf: 1 } },
    },
    {
      id: 'lateral_hop', name: 'Lateral hop', type: 'reps', view: 'front', tracking: 'none', level: 'advanced', equipment: ['none', 'a line or low object to clear'],
      muscles: { primary: ['calves', 'quadriceps'], secondary: ['gluteus medius', 'ankle stabilisers'] }, sided: { limb: 'leg', by: 'pick' },
      summary: 'Hop side to side over a line on one leg, landing softly with the knee over the toes.',
      setup: 'Stand on one leg beside a line, facing the phone. Hop sideways over the line and stick the landing, knee soft and over the middle of the foot, then hop back.',
      why: 'The landing quality is what matters and it happens in a fraction of a second — too fast and too small for the phone to judge honestly. Follow the guide and log the set.',
      camera: { height: 'hip', distance: '2.5 m', posture: 'standing' }, targets: [6, 8, 10, 12], defaultTarget: 8,
      tempo: 'Stick each landing for a second.', dosage: '3 × 8 each leg.', progression: 'Further apart; faster; over a low object.', regression: 'Two-leg hops; smaller distance.',
      contraindications: 'Any pain on landing; recent sprain not yet cleared for hopping.',
      faults: [ { id: 'valgus', label: 'Knee caving on landing', cue: 'Knee over toes', tip: 'Land with the knee tracking over the middle of the foot; if it dives inward, hop smaller.', severity: 3 }, { id: 'stiff', label: 'Landing stiff', cue: 'Land soft', tip: 'Bend the knee and hip on landing so it is quiet; a loud landing is a stiff one.', severity: 2 } ],
      guide: { surface: 'Firm, non-slip floor with a line.', stop: 'Pain on landing.', cannotSee: 'The landing — it is over before the phone can judge it.',
        regions: [{ name: 'Landing', points: [{ t: 'Soft, quiet, knee over the middle toes, hips level.', tracked: false }] }] },
      pose: { A: { legL: 22, shinL: 0, legR: 2, squat: .3, armL: 30, armR: 30 }, B: { legR: 2, squat: .05, legL: 26, shinL: 6, armL: 45, armR: 45 }, work: { calf: 1, thigh: .8, glute: .6 } },
    },
    {
      id: 'soleus_stretch', name: 'Soleus stretch (bent knee)', type: 'hold', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['wall'],
      muscles: { primary: ['soleus'], secondary: ['Achilles tendon'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'The wall calf stretch with the back knee bent, to reach the deeper calf muscle.',
      setup: 'Hands on a wall, working leg back and nearest the phone, heel down. Bend the back knee while keeping the heel on the floor until the stretch moves lower into the calf. Hold.',
      why: 'The timer runs while the back knee is bent — the difference between this and the straight-leg calf stretch.',
      targets: [20, 30, 45, 60], defaultTarget: 30,
      hold: { conditions: [{ metric: KNEE, max: 155 }] },
      tempo: 'Ease in over 5 s, hold, ease out.', dosage: '3 × 30 s each leg.', progression: 'Toes on a book to add range.', regression: 'Smaller knee bend.',
      contraindications: 'Achilles pain that sharpens in the stretch.',
      faults: [ { id: 'heel', label: 'Heel lifting', cue: 'Heel down', tip: 'If the heel comes up, bring the foot closer to the wall.', severity: 2 }, { id: 'straight', label: 'Knee straightening', cue: 'Keep the knee bent', tip: 'The bent knee is what moves the stretch to the soleus; keep it soft.', severity: 2 } ],
      guide: { surface: 'Floor with grip and a wall.', stop: 'Sharp Achilles pain.', cannotSee: 'The heel lifting slightly.',
        regions: [{ name: 'Back leg', points: [{ t: 'Knee bent, heel planted, toes pointing at the wall.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Hands on the wall, hips square.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: 12, thigh: -18, shin: 10, thighF: 30, shinF: -30, uarm: 70, farm: 70 }, B: { face: 'right', torso: 14, thigh: -22, shin: 22, thighF: 32, shinF: -32, uarm: 72, farm: 72 }, work: { calf: 1 }, wall: 'ahead' },
    },
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
