/* Core — catalogue moves. Data only; see coach/catalog.js for the fields and docs/EXERCISE-LIBRARY.md. */
(function (root) {
  'use strict';
  const C = (typeof module !== 'undefined' && module.exports) ? require('../catalog.js') : root.FyzioCatalog;
  const supine = { face: 'right', torso: -90, uarm: 90, farm: 90 };
  const quadruped = { face: 'left', torso: -88, neck: -25, thigh: 0, shin: -90, uarm: 0, farm: 0 };
  const SAG = { kind: 'offset', pts: ['SH', 'KNEE', 'HIP'] };

  C.defineCatalog({
    region: 'core', group: 'Core', order: 1600,
    camera: { height: 'floor', distance: '2 m', posture: 'lying' },
    sources: [
      { name: 'McGill — the Big 3 (Backfitpro)', url: 'https://www.backfitpro.com/' },
      { name: 'ACE — core exercises', url: 'https://www.acefitness.org/resources/everyone/exercise-library/' },
      { name: 'E3 Rehab — core stability', url: 'https://e3rehab.com/' },
    ],
  }, [
    {
      id: 'dead_bug', name: 'Dead bug', type: 'reps', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['mat'],
      muscles: { primary: ['abdominals', 'transversus abdominis'], secondary: ['hip flexors', 'shoulders'] },
      summary: 'On your back with arms up and knees over the hips, lower one arm and the opposite leg, then return.',
      setup: 'Lie on your back, side-on to the phone at floor level, arms pointing at the ceiling, hips and knees at 90°. Brace, lower one arm overhead and the opposite leg toward the floor, stop before the back arches, return. Alternate.',
      why: 'From the side the near arm swings from vertical to overhead each rep, which counts. The lower back arching — the fault that matters — is hidden by the floor.',
      progress: { metric: { kind: 'vertical', pts: ['SH', 'WR'] }, start: 'calibrated', target: 145 },
      tempo: 'Lower 3 s, return 2 s.', dosage: '3 × 8 each side.', progression: 'Arm and leg fully straight; a light weight in the hand.', regression: 'Arm only, or leg only; heel taps.',
      contraindications: 'Back pain that increases as the limbs lower.',
      faults: [ { id: 'arch', label: 'Lower back arching', cue: 'Back flat', tip: 'Lower only as far as the back can stay pressed into the floor; shorter range is fine.', severity: 3 }, { id: 'breath', label: 'Holding the breath', cue: 'Breathe out lowering', tip: 'The exhale keeps the ribs down and the brace on.', severity: 1 } ],
      guide: { surface: 'Firm floor or mat.', stop: 'Back pain during the lowering.', cannotSee: 'The lower back leaving the floor.', regions: [{ name: 'Arm', points: [{ t: 'Lowers overhead, straight.', tracked: true }] }, { name: 'Leg', points: [{ t: 'Opposite leg lowers, knee bent or straight.', tracked: false }] }, { name: 'Back', points: [{ t: 'Pressed into the floor throughout.', tracked: false }] }] },
      pose: { A: { ...supine, thigh: 90, shin: 0, foot: 60, thighF: 90, shinF: 0, uarm: 180, farm: 180, uarmF: 180, farmF: 180 }, B: { ...supine, thigh: 110, shin: 60, foot: 90, thighF: 90, shinF: 0, uarm: 110, farm: 110, uarmF: 180, farmF: 180 }, work: { abs: 1 } },
    },
    {
      id: 'plank_knees', name: 'Plank on the knees', type: 'hold', view: 'side', tracking: 'form', level: 'beginner', equipment: ['mat'],
      muscles: { primary: ['abdominals', 'transversus abdominis'], secondary: ['shoulders', 'gluteus maximus'] },
      summary: 'Forearms and knees on the floor, body a straight line from head to knee, hold.',
      setup: 'Kneel side-on to the phone at floor level, forearms on the mat, elbows under the shoulders. Walk the knees back until the body is a straight line from shoulder to knee. Brace and hold.',
      why: 'From the side the hips should sit on the line from shoulder to knee. Sagging below it or piking above it is measured directly.',
      camera: { height: 'floor', distance: '2 m', posture: 'kneeling' }, targets: [15, 20, 30, 45, 60], defaultTarget: 30,
      hold: { conditions: [{ metric: SAG, min: -8, max: 10 }] },
      tempo: 'Still; breathe.', dosage: '3 × 30 s.', progression: 'Full plank on the toes.', regression: 'Hands instead of forearms; shorter holds.',
      contraindications: 'Shoulder pain on the forearms; back pain in the hold.',
      faults: [
        { id: 'sag', label: 'Hips sagging', cue: 'Hips up', tip: 'Squeeze the buttocks and draw the stomach in so the hips lift back onto the line.', severity: 3, metric: SAG, op: '>', threshold: 10, phase: 'hold', persist: 600, cooldown: 6000 },
        { id: 'pike', label: 'Hips too high', cue: 'Hips down', tip: 'A tent shape rests the abs. Lower the hips until the body is one line.', severity: 2, metric: SAG, op: '<', threshold: -8, phase: 'hold', persist: 600, cooldown: 6000 },
        { id: 'head', label: 'Head dropping', cue: 'Look at the floor ahead', tip: 'The neck is part of the line; look a hand-width ahead of the fingers.', severity: 1 },
      ],
      guide: { surface: 'A mat under knees and forearms.', stop: 'Shoulder or back pain.', cannotSee: 'How hard the stomach is braced.', regions: [{ name: 'Body line', points: [{ t: 'Straight from shoulder to knee — no sag, no pike.', tracked: true }] }, { name: 'Elbows', points: [{ t: 'Under the shoulders.', tracked: false }] }] },
      pose: { A: { face: 'left', torso: 72, neck: -15, thigh: -69, shin: -140, foot: -30, uarm: -20, farm: 90 }, B: { face: 'left', torso: 72, neck: -15, thigh: -69, shin: -140, foot: -30, uarm: -20, farm: 90 }, work: { abs: 1, shoulder: .4, glute: .3 } },
    },
    {
      id: 'side_plank', name: 'Side plank', type: 'hold', view: 'side', tracking: 'form', level: 'intermediate', equipment: ['mat'],
      muscles: { primary: ['obliques', 'quadratus lumborum'], secondary: ['gluteus medius', 'shoulders'] }, sided: { limb: 'arm', by: 'camera' },
      summary: 'On one forearm and the side of the feet, lift the hips so the body is a straight line.',
      setup: 'Lie on one side facing the phone, forearm on the floor with the elbow under the shoulder, feet stacked or staggered. Lift the hips until shoulder, hip and ankle are in line. Hold.',
      why: 'Facing the phone the body is one line from shoulder to ankle; the hip dropping below it is measured directly.',
      camera: { height: 'floor', distance: '2 m', posture: 'sidelying' }, targets: [15, 20, 30, 45], defaultTarget: 20,
      hold: { conditions: [{ metric: { kind: 'offset', pts: ['SH', 'ANK', 'HIP'] }, max: 8 }] },
      tempo: 'Still; breathe.', dosage: '3 × 20–30 s each side.', progression: 'Feet stacked; top leg lifted.', regression: 'From the knees.',
      contraindications: 'Shoulder pain on the supporting arm.',
      faults: [
        { id: 'drop', label: 'Hips dropping', cue: 'Hips up', tip: 'Push the floor away with the forearm and lift the lower hip until the body is straight.', severity: 3, metric: { kind: 'offset', pts: ['SH', 'ANK', 'HIP'] }, op: '>', threshold: 8, phase: 'hold', persist: 600, cooldown: 6000 },
        { id: 'roll', label: 'Rolling forward', cue: 'Chest to the phone', tip: 'Stack the shoulders and hips; the top hip should not fall forward.', severity: 2 },
      ],
      guide: { surface: 'A mat under the forearm.', stop: 'Shoulder pain.', cannotSee: 'Rolling forward or back.', regions: [{ name: 'Body line', points: [{ t: 'Shoulder, hip and ankle in one line.', tracked: true }] }, { name: 'Elbow', points: [{ t: 'Directly under the shoulder.', tracked: false }] }] },
      pose: { A: { face: 'left', torso: 76, neck: -10, thigh: -76, shin: -76, foot: -40, uarm: 0, farm: 90, uarmF: 180, farmF: 180 }, B: { face: 'left', torso: 76, neck: -10, thigh: -76, shin: -76, foot: -40, uarm: 0, farm: 90, uarmF: 180, farmF: 180 }, work: { oblique: 1, glute: .5, shoulder: .4 } },
    },
    {
      id: 'bird_dog', name: 'Bird dog', type: 'hold', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['mat'],
      muscles: { primary: ['spinal erectors', 'abdominals', 'gluteus maximus'], secondary: ['shoulders'] }, sided: { limb: 'arm', by: 'camera' },
      summary: 'On hands and knees, reach one arm forward and the opposite leg back, hold, return.',
      setup: 'Hands under the shoulders, knees under the hips, side-on to the phone at knee height. Reach the near arm forward and the far leg back until both are level with the back. Hold without the back twisting, then return.',
      why: 'From the side the reaching arm and the extended leg both approach horizontal, so the timer runs only while both are held up.',
      camera: { height: 'knee', distance: '2 m', posture: 'kneeling' }, targets: [5, 8, 10, 15], defaultTarget: 8,
      hold: { conditions: [{ metric: { kind: 'vertical', pts: ['SH', 'WR'] }, min: 80 }, { metric: { kind: 'vertical', pts: ['oHIP', 'oKNEE'] }, min: 80 }] },
      tempo: 'Reach 2 s, hold, return 2 s.', dosage: '3 × 8 holds each side.', progression: 'Longer holds; draw the elbow and knee together between reps.', regression: 'Arm only, then leg only.',
      contraindications: 'Wrist pain that stops weight-bearing.',
      faults: [ { id: 'twist', label: 'Hips twisting', cue: 'Hips level', tip: 'Imagine a glass of water on the lower back; the leg lifts only as high as the hips can stay square.', severity: 3 }, { id: 'arch', label: 'Lower back arching', cue: 'Ribs down', tip: 'Lift the leg to level with the back, no higher.', severity: 2 } ],
      guide: { surface: 'A mat under the knees.', stop: 'Wrist or back pain.', cannotSee: 'The hips twisting.', regions: [{ name: 'Arm', points: [{ t: 'Reaches forward to level.', tracked: true }] }, { name: 'Leg', points: [{ t: 'Extends back to level, not above.', tracked: true }] }, { name: 'Back', points: [{ t: 'Flat and square throughout.', tracked: false }] }] },
      pose: { A: { ...quadruped }, B: { ...quadruped, uarm: 178, farm: 178, thighF: 88, shinF: 90, footF: -60 }, work: { back: 1, glute: .8, abs: .6, shoulder: .4 } },
    },
    {
      id: 'mcgill_curl_up', name: 'McGill curl-up', type: 'hold', view: 'side', tracking: 'none', level: 'beginner', equipment: ['mat'],
      muscles: { primary: ['rectus abdominis', 'transversus abdominis'], secondary: [] },
      summary: 'One knee bent, hands under the lower back, lift the head and shoulders a few centimetres and hold.',
      setup: 'Lie on your back, one knee bent, hands under the natural curve of the lower back. Brace and lift the head and shoulders just off the floor without bending the neck. Hold, lower.',
      why: 'The lift is a couple of centimetres and the neck must not flex, which is exactly the detail a phone cannot judge. Logged by hand.',
      targets: [8, 10, 15], defaultTarget: 10,
      tempo: 'Hold 8–10 s, rest 3 s.', dosage: '5, 3, 1 holds (descending pyramid), daily.', progression: 'Elbows off the floor.', regression: 'Shorter holds; head barely lifting.',
      contraindications: 'Neck pain on the lift.',
      faults: [ { id: 'neck', label: 'Chin poking forward', cue: 'Head and chest as one', tip: 'The head and shoulders lift together as a block; the neck does not curl.', severity: 2 }, { id: 'high', label: 'Lifting too high', cue: 'Just off the floor', tip: 'The lift is small on purpose; higher loads the spine without adding much for the abs.', severity: 1 } ],
      guide: { surface: 'Firm floor.', stop: 'Neck pain.', cannotSee: 'The size of the lift.', regions: [{ name: 'Head and chest', points: [{ t: 'Lift as one block, barely off the floor.', tracked: false }] }, { name: 'Lower back', points: [{ t: 'Curve preserved over the hands.', tracked: false }] }] },
      pose: { A: { ...supine, thigh: 130, shin: -25, thighF: 90, shinF: 90, uarm: 30, farm: 150 }, B: { ...supine, torso: -78, neck: -6, thigh: 130, shin: -25, thighF: 90, shinF: 90, uarm: 30, farm: 150 }, work: { abs: 1 } },
    },
    {
      id: 'hollow_hold', name: 'Hollow hold', type: 'hold', view: 'side', tracking: 'reps', level: 'intermediate', equipment: ['mat'],
      muscles: { primary: ['rectus abdominis', 'hip flexors'], secondary: ['quadriceps'] },
      summary: 'On your back, press the lower back down and lift the legs and shoulders so the body is a shallow banana.',
      setup: 'Lie on your back, side-on to the phone at floor level. Press the lower back into the floor, lift the straight legs and the shoulders a little, arms by the sides or overhead. Hold.',
      why: 'From the side the legs are held above the floor, so the timer runs while they stay up. The back arching is hidden.',
      targets: [10, 15, 20, 30, 45], defaultTarget: 20,
      hold: { conditions: [{ metric: { kind: 'vertical', pts: ['HIP', 'KNEE'] }, min: 110 }] },
      tempo: 'Still; breathe.', dosage: '3 × 20 s.', progression: 'Legs lower; arms overhead.', regression: 'Knees bent, or one leg at a time.',
      contraindications: 'Lower back pain in the hold.',
      faults: [ { id: 'arch', label: 'Lower back arching', cue: 'Back into the floor', tip: 'Raise the legs higher until the back can stay flat; lower them over weeks.', severity: 3 }, { id: 'neck', label: 'Neck straining', cue: 'Chin tucked', tip: 'Look at the knees, not the ceiling.', severity: 1 } ],
      guide: { surface: 'Firm floor or mat.', stop: 'Lower back pain.', cannotSee: 'The lower back leaving the floor.', regions: [{ name: 'Legs', points: [{ t: 'Straight, held off the floor.', tracked: true }] }, { name: 'Back', points: [{ t: 'Flat on the floor; shoulders slightly lifted.', tracked: false }] }] },
      pose: { A: { ...supine, thigh: 90, shin: 90, foot: 90 }, B: { ...supine, torso: -78, thigh: 112, shin: 112, foot: 112, uarm: 160, farm: 160 }, work: { abs: 1, thigh: .3 } },
    },
    {
      id: 'pallof_press', name: 'Pallof press', type: 'reps', view: 'front', tracking: 'none', level: 'intermediate', equipment: ['resistance band', 'anchor point'],
      muscles: { primary: ['obliques', 'transversus abdominis'], secondary: ['shoulders'] }, band: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'Band anchored to one side, held at the chest; press it straight out and resist the twist.',
      setup: 'Anchor a band at chest height to one side. Stand side-on to the anchor, holding the band at the chest with both hands, feet hip-width. Press the hands straight out in front, hold two seconds, bring them back. Do not let the band turn you.',
      why: 'The press moves toward the phone and the twist it resists is invisible. Logged by hand.',
      camera: { height: 'chest', distance: '2 m', posture: 'standing' },
      tempo: 'Press 1 s, hold 2 s, return 1 s.', dosage: '3 × 10 each side.', progression: 'Heavier band; half-kneeling; hold the press longer.', regression: 'Lighter band; stand closer to the anchor.',
      contraindications: 'Back pain on the twist.',
      faults: [ { id: 'twist', label: 'Turning toward the anchor', cue: 'Hips and chest square', tip: 'Brace before the press; the point is to not move.', severity: 3 }, { id: 'lean', label: 'Leaning away', cue: 'Stay tall', tip: 'Leaning away uses body weight instead of the core. Stand tall and let the abs do it.', severity: 2 } ],
      guide: { surface: 'Any floor; a solid anchor.', stop: 'Back pain.', cannotSee: 'The press and the twist it resists.', regions: [{ name: 'Trunk', points: [{ t: 'Square to the front; no twist, no lean.', tracked: false }] }, { name: 'Arms', points: [{ t: 'Press straight out and return.', tracked: false }] }] },
      pose: { A: { armL: 30, foreL: 100, armR: 30, foreR: 100, legL: 8, legR: 8 }, B: { armL: 12, foreL: 90, armR: 12, foreR: 90, legL: 8, legR: 8 }, work: { oblique: 1, abs: .6, shoulder: .3 } },
    },
    {
      id: 'bicycle_crunch', name: 'Bicycle crunch', type: 'reps', view: 'side', tracking: 'none', level: 'intermediate', equipment: ['mat'],
      muscles: { primary: ['rectus abdominis', 'obliques'], secondary: ['hip flexors'] },
      summary: 'Hands by the ears, bring one elbow toward the opposite knee as the other leg extends, alternating.',
      setup: 'Lie on your back, hands lightly behind the ears, knees lifted. Bring the right elbow toward the left knee while the right leg straightens, then switch sides with control.',
      why: 'Legs and elbows cross in front of each other from every angle; the rep count is not reliable. Logged by hand.',
      tempo: 'Slow and controlled, 1 s per side.', dosage: '3 × 20 (10 each side).', progression: 'Slower; legs closer to the floor.', regression: 'Feet on the floor; one side at a time.',
      contraindications: 'Neck or lower back pain.',
      faults: [ { id: 'neck', label: 'Pulling on the neck', cue: 'Hands light', tip: 'Fingertips only; turn the chest, not the head.', severity: 2 }, { id: 'rush', label: 'Rushing', cue: 'Slow the pedal', tip: 'Speed lets momentum do the work; two seconds per side.', severity: 1 } ],
      guide: { surface: 'Firm floor or mat.', stop: 'Neck or back pain.', cannotSee: 'Almost everything — limbs cross.', regions: [{ name: 'Trunk', points: [{ t: 'Rotates from the ribs; shoulder lifts toward the knee.', tracked: false }] }, { name: 'Legs', points: [{ t: 'Alternate; the straight leg stays off the floor.', tracked: false }] }] },
      pose: { A: { ...supine, torso: -75, thigh: 165, shin: -100, thighF: 100, shinF: 100, footF: 100, uarm: 150, farm: 60 }, B: { ...supine, torso: -75, thigh: 100, shin: 100, foot: 100, thighF: 165, shinF: -100, uarm: 150, farm: 60 }, work: { abs: 1, oblique: .8 } },
    },
    {
      id: 'leg_lower', name: 'Double leg lowering', type: 'reps', view: 'side', tracking: 'reps', level: 'intermediate', equipment: ['mat'],
      muscles: { primary: ['rectus abdominis', 'hip flexors'], secondary: [] },
      summary: 'Legs straight up, lower them slowly toward the floor and stop before the back arches.',
      setup: 'Lie on your back, side-on to the phone at floor level, legs straight and pointing at the ceiling. Press the back down and lower the legs as far as it stays flat, then lift back up.',
      why: 'From the side the leg angle from the floor drops and returns every rep, which counts. The back arching is hidden.',
      progress: { metric: { kind: 'vertical', pts: ['HIP', 'KNEE'] }, start: 'calibrated', target: 105 }, minMs: 2000,
      tempo: 'Lower 3–4 s, lift 2 s.', dosage: '3 × 8.', progression: 'Lower further; arms overhead.', regression: 'One leg at a time; knees bent.',
      contraindications: 'Back pain during the lowering.',
      faults: [ { id: 'arch', label: 'Lower back arching', cue: 'Stop before the back lifts', tip: 'Range is earned; lower only as far as the floor stays under the lower back.', severity: 3 }, { id: 'drop', label: 'Dropping the legs', cue: 'Slow on the way down', tip: 'The lowering is the exercise. Three seconds minimum.', severity: 1 } ],
      guide: { surface: 'Firm floor or mat.', stop: 'Back pain.', cannotSee: 'The lower back arching.', regions: [{ name: 'Legs', points: [{ t: 'Straight, lowering together.', tracked: true }] }, { name: 'Back', points: [{ t: 'Flat on the floor.', tracked: false }] }] },
      pose: { A: { ...supine, thigh: 175, shin: 175, foot: 175, uarm: 90, farm: 90 }, B: { ...supine, thigh: 115, shin: 115, foot: 115, uarm: 90, farm: 90 }, work: { abs: 1 } },
    },
    {
      id: 'superman', name: 'Superman', type: 'reps', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['mat'],
      muscles: { primary: ['spinal erectors', 'gluteus maximus'], secondary: ['hamstrings', 'shoulders'] },
      summary: 'Face down, lift the arms and legs a few centimetres off the floor together, hold, lower.',
      setup: 'Lie on your front, side-on to the phone at floor level, arms overhead. Lift arms, chest and legs off the floor together, hold two seconds, lower slowly.',
      why: 'From the side the shoulder line rises against the hip each rep, so reps are counted. Lifting too high is not judged.',
      camera: { height: 'floor', distance: '2 m', posture: 'prone' },
      progress: { metric: { kind: 'vertical', pts: ['HIP', 'SH'] }, start: 'calibrated', target: 12, targetIsDelta: true },
      tempo: 'Lift 2 s, hold 2 s, lower 2 s.', dosage: '3 × 10.', progression: 'Longer holds; opposite arm and leg.', regression: 'Arms only, then legs only.',
      contraindications: 'Pain in the lower back at the top.',
      faults: [ { id: 'high', label: 'Lifting too high', cue: 'A few centimetres', tip: 'Higher pinches the lower back; a small lift with a long reach is the aim.', severity: 2 }, { id: 'neck', label: 'Looking up', cue: 'Look at the floor', tip: 'The head stays in line with the spine.', severity: 1 } ],
      guide: { surface: 'A mat.', stop: 'Lower back pain.', cannotSee: 'How high the legs are — the arms hide them.', regions: [{ name: 'Upper body', points: [{ t: 'Chest and arms lift a little; long reach.', tracked: true }] }, { name: 'Legs', points: [{ t: 'Lift together, knees straight.', tracked: false }] }] },
      pose: { A: { face: 'left', torso: -90, thigh: 90, shin: 90, foot: -70, uarm: 178, farm: 178 }, B: { face: 'left', torso: -78, neck: -5, thigh: 100, shin: 100, foot: -60, uarm: 170, farm: 170 }, work: { back: 1, glute: .8, shoulder: .3 } },
    },
    {
      id: 'supine_march', name: 'Supine march', type: 'reps', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['mat'],
      muscles: { primary: ['transversus abdominis', 'hip flexors'], secondary: [] },
      summary: 'Lying with knees bent, brace and lift one foot off the floor, lower, then the other.',
      setup: 'Lie on your back, knees bent, feet flat, side-on to the phone at floor level. Brace the stomach and lift one foot until the knee is over the hip, lower with control, then the other.',
      why: 'From the side the near thigh rises toward vertical on every lift, so reps are counted. The pelvis rocking is not measured.',
      progress: { metric: { kind: 'vertical', pts: ['HIP', 'KNEE'] }, start: 'calibrated', target: 25, targetIsDelta: true },
      tempo: 'Lift 2 s, lower 2 s.', dosage: '3 × 10 each leg.', progression: 'Hold the top; progress to dead bug.', regression: 'Heel slides.',
      contraindications: 'Back pain as the foot lifts.',
      faults: [ { id: 'rock', label: 'Pelvis rocking', cue: 'Hips still', tip: 'Brace before the foot lifts; if the pelvis rocks, lift the foot less.', severity: 2 }, { id: 'breath', label: 'Holding the breath', cue: 'Breathe out to lift', tip: 'Exhale on the lift and the brace stays on without straining.', severity: 1 } ],
      guide: { surface: 'Firm floor or mat.', stop: 'Back pain.', cannotSee: 'The pelvis rocking.', regions: [{ name: 'Leg', points: [{ t: 'Knee lifts over the hip, foot relaxed.', tracked: true }] }, { name: 'Pelvis', points: [{ t: 'Still and level.', tracked: false }] }] },
      pose: { A: { ...supine, thigh: 130, shin: -25, thighF: 130, shinF: -25 }, B: { ...supine, thigh: 165, shin: -5, thighF: 130, shinF: -25 }, work: { abs: 1 } },
    },
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
