/* Elbow, wrist and hand — catalogue moves. Data only; see coach/catalog.js and docs/EXERCISE-LIBRARY.md.
   The pose model stops at the wrist, so almost everything here is guide + hand-logged. */
(function (root) {
  'use strict';
  const C = (typeof module !== 'undefined' && module.exports) ? require('../catalog.js') : root.FyzioCatalog;
  const seated = { face: 'right', torso: 0, thigh: 90, shin: 0 };
  const ELBOW = { kind: 'angle', pts: ['SH', 'EL', 'WR'] };

  C.defineCatalog({
    region: 'elbow', group: 'Elbow, wrist & hand', order: 1700,
    camera: { height: 'chest', distance: '1.5 m', posture: 'sitting' },
    sources: [
      { name: 'Physiopedia — lateral epicondylitis exercises', url: 'https://www.physio-pedia.com/Lateral_Epicondylitis' },
      { name: 'Tyler & Thomas — eccentric training with the FlexBar (Tyler twist)', url: 'https://pubmed.ncbi.nlm.nih.gov/20303293/' },
      { name: 'ASSH — hand and wrist exercises', url: 'https://www.assh.org/handcare/' },
      { name: 'NHS — tennis elbow exercises', url: 'https://www.nhs.uk/conditions/tennis-elbow/' },
    ],
  }, [
    {
      id: 'eccentric_wrist_ext', name: 'Eccentric wrist extension', type: 'reps', view: 'front', tracking: 'none', level: 'beginner', equipment: ['light dumbbell or tin'],
      muscles: { primary: ['wrist extensors'], secondary: ['grip'] }, upperBody: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'Forearm on a table, palm down, lift the weight with the other hand and lower it slowly with the working wrist.',
      setup: 'Sit with the forearm resting on a table, wrist over the edge, palm down, a light weight in the hand. Use the other hand to lift the wrist up, then lower it slowly on its own over three to five seconds.',
      why: 'The wrist tilts a few centimetres at the edge of a table — below what the pose model resolves. Logged by hand.',
      tempo: 'Lower 3–5 s, assist up.', dosage: '3 × 15, daily for tennis elbow.', progression: 'Heavier weight; slower lowering.', regression: 'No weight; shorter range.',
      contraindications: 'Sharp pain at the outside of the elbow that lingers after the set.',
      faults: [ { id: 'fast', label: 'Dropping the wrist', cue: 'Slow on the way down', tip: 'The slow lowering is the whole point; the way up is assisted.', severity: 2 }, { id: 'lift', label: 'Forearm lifting off the table', cue: 'Forearm flat', tip: 'Only the wrist moves; pin the forearm down.', severity: 1 } ],
      guide: { surface: 'A table with the wrist over the edge.', stop: 'Sharp elbow pain that lingers.', cannotSee: 'The wrist movement.', regions: [{ name: 'Wrist', points: [{ t: 'Lowers slowly from up to hanging.', tracked: false }] }, { name: 'Forearm', points: [{ t: 'Flat on the table.', tracked: false }] }] },
      pose: { A: { armL: 8, armR: 70, foreR: 100 }, B: { armL: 8, armR: 70, foreR: 96 }, work: { forearm: 1 } },
    },
    {
      id: 'wrist_curl', name: 'Wrist curl', type: 'reps', view: 'front', tracking: 'none', level: 'beginner', equipment: ['light dumbbell'],
      muscles: { primary: ['wrist flexors'], secondary: ['grip'] }, upperBody: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'Forearm on the thigh, palm up, curl the weight up with the wrist and lower.',
      setup: 'Sit with the forearm on the thigh, wrist past the knee, palm up, light weight in the hand. Curl the wrist up, hold a second, lower slowly.',
      why: 'The movement is a few centimetres of hand travel. Logged by hand.',
      tempo: 'Up 2 s, down 3 s.', dosage: '3 × 15.', progression: 'Heavier weight.', regression: 'No weight.',
      contraindications: 'Pain at the inside of the elbow (golfer\'s elbow) that grows during the set.',
      faults: [ { id: 'elbow', label: 'Elbow lifting', cue: 'Elbow down', tip: 'If the elbow rises the biceps are helping; keep it pinned on the thigh.', severity: 2 }, { id: 'fast', label: 'Rushing', cue: 'Slow it down', tip: 'Three seconds to lower.', severity: 1 } ],
      guide: { surface: 'A chair; forearm on the thigh.', stop: 'Pain on the inside of the elbow.', cannotSee: 'The wrist movement.', regions: [{ name: 'Wrist', points: [{ t: 'Curls up and lowers fully.', tracked: false }] }] },
      pose: { A: { armL: 8, armR: 25, foreR: 100 }, B: { armL: 8, armR: 25, foreR: 104 }, work: { forearm: 1 } },
    },
    {
      id: 'pronation_supination', name: 'Forearm rotation (pronation / supination)', type: 'reps', view: 'front', tracking: 'none', level: 'beginner', equipment: ['hammer or light dumbbell held at one end'],
      muscles: { primary: ['pronator teres', 'supinator'], secondary: ['biceps'] }, upperBody: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'Elbow at 90° by the side, turn the palm up and then down with a hammer in the hand.',
      setup: 'Sit or stand with the elbow tucked and bent to 90°, holding a hammer near the head end. Turn the palm up until the hammer points sideways, then down the other way. Slow and controlled.',
      why: 'The forearm rotates on its own axis; the wrist barely changes position. Logged by hand.',
      tempo: '2 s each way.', dosage: '3 × 10 each way.', progression: 'Hold the hammer lower on the handle.', regression: 'No weight.',
      contraindications: 'Sharp elbow pain on rotation.',
      faults: [ { id: 'elbow', label: 'Elbow drifting away from the side', cue: 'Elbow tucked', tip: 'Tuck a towel under the arm to keep the elbow still.', severity: 2 }, { id: 'shoulder', label: 'Shoulder rotating', cue: 'Only the forearm turns', tip: 'If the elbow swings in and out, the shoulder is turning instead.', severity: 1 } ],
      guide: { surface: 'Anywhere.', stop: 'Sharp elbow pain.', cannotSee: 'The rotation.', regions: [{ name: 'Forearm', points: [{ t: 'Rotates fully palm up and palm down.', tracked: false }] }, { name: 'Elbow', points: [{ t: 'Tucked and still.', tracked: false }] }] },
      pose: { A: { armL: 8, armR: 8, foreR: 90 }, B: { armL: 8, armR: 8, foreR: 92 }, work: { forearm: 1 } },
    },
    {
      id: 'tyler_twist', name: 'Tyler twist (FlexBar)', type: 'reps', view: 'front', tracking: 'none', level: 'beginner', equipment: ['FlexBar or rolled towel'],
      muscles: { primary: ['wrist extensors'], secondary: ['grip'] }, upperBody: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'Twist a rubber bar with the good hand, then let the sore side untwist it slowly.',
      setup: 'Hold the bar vertically in the sore hand, wrist bent back. Grip the top with the other hand and twist it. Bring both arms straight out in front, then slowly let the sore wrist straighten so the bar untwists.',
      why: 'The action is inside the hands. Logged by hand.',
      tempo: 'Untwist over 4 s.', dosage: '3 × 15, daily.', progression: 'Stiffer bar.', regression: 'Softer bar or a rolled towel.',
      contraindications: 'Pain that stays after the set, or a numb hand.',
      faults: [ { id: 'fast', label: 'Untwisting too fast', cue: 'Four seconds', tip: 'The slow untwist loads the tendon; fast is wasted.', severity: 2 }, { id: 'elbow', label: 'Elbows bending', cue: 'Arms straight', tip: 'Keep both elbows straight so the wrist does the work.', severity: 1 } ],
      guide: { surface: 'Anywhere.', stop: 'Pain that lingers or a numb hand.', cannotSee: 'The twist.', regions: [{ name: 'Sore wrist', points: [{ t: 'Straightens slowly against the bar.', tracked: false }] }] },
      pose: { A: { armL: 88, foreL: 88, armR: 88, foreR: 88 }, B: { armL: 88, foreL: 88, armR: 88, foreR: 88 }, work: { forearm: 1 } },
    },
    {
      id: 'grip_squeeze', name: 'Grip squeeze', type: 'hold', view: 'front', tracking: 'none', level: 'beginner', equipment: ['soft ball or putty'],
      muscles: { primary: ['finger flexors', 'grip'], secondary: ['wrist flexors'] }, upperBody: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'Squeeze a soft ball as hard as is comfortable, hold, relax.',
      setup: 'Hold a soft ball or putty in the palm. Squeeze, hold five seconds, relax fully.',
      why: 'The fingers do all the work. Logged by hand.',
      targets: [5, 8, 10], defaultTarget: 5,
      tempo: 'Squeeze 5 s, relax 3 s.', dosage: '10 × 5 s, 2–3 times a day.', progression: 'Firmer putty; longer holds.', regression: 'Lighter squeeze.',
      contraindications: 'Pain in the fingers or a recent hand fracture without clearance.',
      faults: [ { id: 'wrist', label: 'Wrist bending on the squeeze', cue: 'Wrist straight', tip: 'Keep the wrist neutral so the fingers do the work.', severity: 1 }, { id: 'breath', label: 'Holding the breath', cue: 'Keep breathing', tip: 'Count out loud.', severity: 1 } ],
      guide: { surface: 'Anywhere.', stop: 'Finger pain.', cannotSee: 'The squeeze.', regions: [{ name: 'Hand', points: [{ t: 'Squeezes evenly with all fingers.', tracked: false }] }] },
      pose: { A: { armL: 8, armR: 20, foreR: 100 }, B: { armL: 8, armR: 20, foreR: 100 }, work: { forearm: 1 } },
    },
    {
      id: 'tendon_glides', name: 'Tendon glides', type: 'reps', view: 'front', tracking: 'none', level: 'beginner', equipment: ['none'],
      muscles: { primary: ['finger flexors (glide)'], secondary: [] }, upperBody: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'Move the fingers through straight, hook, fist, tabletop and straight fist positions.',
      setup: 'Hold the hand up, fingers straight. Curl into a hook (fingertips to the base of the fingers), then a full fist, then a tabletop (knuckles bent, fingers straight), then a straight fist. Return to straight each time.',
      why: 'Finger positions are below what the pose model tracks. Logged by hand.',
      tempo: 'Hold each position 3 s.', dosage: '10 cycles, 3 times a day.', progression: 'Add a light stretch at each position.', regression: 'Fewer positions.',
      contraindications: 'Sharp pain or catching in a finger.',
      faults: [ { id: 'skip', label: 'Skipping positions', cue: 'All five shapes', tip: 'Each shape glides a different tendon; go through them all.', severity: 1 }, { id: 'wrist', label: 'Wrist bending', cue: 'Wrist straight', tip: 'Keep the wrist neutral so the glide is in the fingers.', severity: 1 } ],
      guide: { surface: 'Anywhere.', stop: 'Sharp pain in a finger.', cannotSee: 'The fingers.', regions: [{ name: 'Fingers', points: [{ t: 'Straight → hook → fist → tabletop → straight fist.', tracked: false }] }] },
      pose: { A: { armL: 8, armR: 20, foreR: 150 }, B: { armL: 8, armR: 20, foreR: 150 }, work: { forearm: .8 } },
    },
    {
      id: 'wrist_flexor_stretch', name: 'Wrist flexor stretch', type: 'hold', view: 'front', tracking: 'none', level: 'beginner', equipment: ['none'],
      muscles: { primary: ['wrist flexors (stretch)'], secondary: [] }, upperBody: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'Arm straight out, palm up, pull the fingers gently back toward you.',
      setup: 'Straighten the arm in front, palm up. With the other hand, draw the fingers back toward the body until the front of the forearm stretches. Hold.',
      why: 'The stretch is at the hand. Logged by hand.',
      targets: [15, 20, 30], defaultTarget: 20,
      tempo: 'Ease in; hold.', dosage: '3 × 20–30 s.', progression: 'Elbow fully locked.', regression: 'Elbow slightly bent.',
      contraindications: 'Tingling in the fingers.',
      faults: [ { id: 'elbow', label: 'Elbow bending', cue: 'Elbow straight', tip: 'A bent elbow takes the stretch off the forearm.', severity: 1 }, { id: 'pull', label: 'Pulling too hard', cue: 'Gentle', tip: 'A stretch, not a pain.', severity: 1 } ],
      guide: { surface: 'Anywhere.', stop: 'Tingling.', cannotSee: 'The wrist angle.', regions: [{ name: 'Arm', points: [{ t: 'Straight, palm up, fingers drawn back.', tracked: false }] }] },
      pose: { A: { armL: 8, armR: 88, foreR: 88 }, B: { armL: 60, foreL: 88, armR: 88, foreR: 88 }, work: { forearm: 1 } },
    },
    {
      id: 'wrist_extensor_stretch', name: 'Wrist extensor stretch', type: 'hold', view: 'front', tracking: 'none', level: 'beginner', equipment: ['none'],
      muscles: { primary: ['wrist extensors (stretch)'], secondary: [] }, upperBody: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'Arm straight out, palm down, press the back of the hand down and toward you.',
      setup: 'Straighten the arm in front, palm down, fingers relaxed. With the other hand, press the back of the hand down and toward the body until the top of the forearm stretches. Hold.',
      why: 'The stretch is at the hand. Logged by hand.',
      targets: [15, 20, 30], defaultTarget: 20,
      tempo: 'Ease in; hold.', dosage: '3 × 20–30 s.', progression: 'Make a loose fist first.', regression: 'Elbow slightly bent.',
      contraindications: 'Tingling in the fingers.',
      faults: [ { id: 'elbow', label: 'Elbow bending', cue: 'Elbow straight', tip: 'A bent elbow takes the stretch off the forearm.', severity: 1 }, { id: 'shrug', label: 'Shoulder rising', cue: 'Shoulder down', tip: 'Keep the shoulder relaxed so the stretch stays in the forearm.', severity: 1 } ],
      guide: { surface: 'Anywhere.', stop: 'Tingling.', cannotSee: 'The wrist angle.', regions: [{ name: 'Arm', points: [{ t: 'Straight, palm down, hand pressed down.', tracked: false }] }] },
      pose: { A: { armL: 8, armR: 88, foreR: 88 }, B: { armL: 60, foreL: 88, armR: 88, foreR: 88 }, work: { forearm: 1 } },
    },
    {
      id: 'triceps_stretch', name: 'Overhead triceps stretch', type: 'hold', view: 'front', tracking: 'reps', level: 'beginner', equipment: ['none'],
      muscles: { primary: ['triceps (stretch)'], secondary: ['latissimus dorsi'] }, upperBody: true, sided: { limb: 'arm', by: 'pick' },
      summary: 'One arm overhead, elbow bent so the hand drops behind the neck; the other hand draws the elbow across.',
      setup: 'Face the phone. Reach the working arm up, bend the elbow so the hand drops behind the head, and use the other hand on the elbow to draw it gently toward the midline. Hold.',
      why: 'Facing the phone the working upper arm is held near vertical, so the timer runs only while the elbow is up.',
      targets: [15, 20, 30], defaultTarget: 20,
      hold: { conditions: [{ metric: { kind: 'vertical', pts: ['SH', 'EL'] }, min: 150 }] },
      tempo: 'Ease in; hold.', dosage: '3 × 20–30 s each arm.', progression: 'Lean gently to the opposite side.', regression: 'Hold the elbow lower.',
      contraindications: 'Shoulder pain overhead.',
      faults: [ { id: 'lean', label: 'Leaning away', cue: 'Stay tall', tip: 'A side lean fakes the stretch; keep the trunk upright.', severity: 1 }, { id: 'shrug', label: 'Shoulder hiking', cue: 'Shoulder down', tip: 'Let the shoulder drop while the elbow points up.', severity: 1 } ],
      guide: { surface: 'Anywhere.', stop: 'Shoulder pain.', cannotSee: 'The hand behind the neck.', regions: [{ name: 'Working arm', points: [{ t: 'Elbow up and drawn toward the midline.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Tall, not leaning.', tracked: false }] }] },
      pose: { A: { armL: 8, armR: 8 }, B: { armL: 150, foreL: 40, armR: 172, foreR: -10 }, work: { arm: 1, back: .3 } },
    },
    {
      id: 'elbow_flex_ext', name: 'Elbow bend and straighten', type: 'reps', view: 'side', tracking: 'form', level: 'beginner', equipment: ['none', 'light weight later'],
      muscles: { primary: ['biceps', 'triceps'], secondary: [] }, upperBody: true, sided: { limb: 'arm', by: 'camera' },
      summary: 'Standing or sitting, bend the elbow fully so the hand comes to the shoulder, then straighten it fully.',
      setup: 'Sit or stand side-on to the phone at chest height, working arm nearest, upper arm hanging by the side. Bend the elbow until the hand reaches the shoulder, then straighten fully. Keep the upper arm still.',
      why: 'From the side the shoulder–elbow–wrist angle runs from straight to fully bent each rep, and the upper arm swinging forward to help shows as the shoulder–elbow line leaving vertical.',
      camera: { height: 'chest', distance: '1.5 m', posture: 'standing' },
      progress: { metric: ELBOW, start: 'calibrated', target: 50 },
      tempo: 'Bend 2 s, straighten 2 s.', dosage: '3 × 10, several times a day after injury.', progression: 'A light weight; a pause at each end.', regression: 'Support the upper arm on a table.',
      contraindications: 'Sharp pain or locking in the joint.',
      faults: [ { id: 'swing', label: 'Upper arm swinging forward', cue: 'Upper arm still', tip: 'Pin the elbow to the side; only the forearm moves.', severity: 2, metric: { kind: 'tilt', pts: ['SH', 'EL'] }, op: '<', threshold: 68, minP: 0.2, persist: 300 }, { id: 'short', label: 'Not straightening fully', cue: 'All the way straight', tip: 'Full straightening is the range that gets lost after injury; finish each rep.', severity: 2 } ],
      guide: { surface: 'Anywhere.', stop: 'Sharp pain or locking.', cannotSee: 'The palm turning.', regions: [{ name: 'Elbow', points: [{ t: 'Bends fully and straightens fully.', tracked: true }] }, { name: 'Upper arm', points: [{ t: 'Hangs still by the side.', tracked: true }] }] },
      pose: { A: { ...seated, uarm: 0, farm: 0 }, B: { ...seated, uarm: 0, farm: 150 }, work: { arm: 1, forearm: .3 } },
    },
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
