/* Gym — lower body, no machines. Data only; see coach/catalog.js and docs/EXERCISE-LIBRARY.md. */
(function (root) {
  'use strict';
  const C = (typeof module !== 'undefined' && module.exports) ? require('../catalog.js') : root.FyzioCatalog;
  const standing = { face: 'right', torso: 0, thigh: 0, shin: 0 };
  const quadruped = { face: 'left', torso: -88, neck: -25, thigh: 0, shin: -90, uarm: 0, farm: 0 };
  const KNEE = { kind: 'angle', pts: ['HIP', 'KNEE', 'ANK'] };
  const TRUNK = { kind: 'tilt', pts: ['SH', 'HIP'] };
  const KNEES_APART = { kind: 'dist', pts: ['KNEE', 'oKNEE'] };
  const valgus = (threshold) => ({ id: 'valgus', label: 'Knees caving inward', cue: 'Knees out', tip: 'Screw the feet into the floor and push the knees over the little toes.', severity: 3, metric: KNEES_APART, rel: 'change', op: '<', threshold: threshold || -12, minP: 0.3, persist: 300 });
  const lean = (threshold) => ({ id: 'lean', label: 'Trunk folding forward', cue: 'Chest up', tip: 'A little forward lean is normal; folding shifts the load to the lower back.', severity: 2, metric: TRUNK, op: '<', threshold, minP: 0.3, persist: 300 });
  const kneesBend = (threshold) => ({ id: 'kneebend', label: 'Knees bending too much', cue: 'Soft knees, hips back', tip: 'The knees stay softly bent while the hips travel back; bending them turns it into a squat.', severity: 2, metric: KNEE, op: '<', threshold, minP: 0.3, persist: 300 });

  C.defineCatalog({
    region: 'gym', group: 'Gym — lower body', order: 1800,
    camera: { height: 'hip', distance: '2.5 m', posture: 'standing' },
    sources: [
      { name: 'ACE Exercise Library', url: 'https://www.acefitness.org/resources/everyone/exercise-library/' },
      { name: 'StrengthLog — exercise directory', url: 'https://www.strengthlog.com/exercise-directory/' },
      { name: 'NSCA — exercise technique', url: 'https://www.nsca.com/education/articles/' },
    ],
  }, [
    {
      id: 'bodyweight_squat', name: 'Bodyweight squat', type: 'reps', view: 'front', tracking: 'form', level: 'beginner', equipment: ['none'],
      muscles: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings', 'adductors', 'core'] },
      summary: 'Feet shoulder-width, sit the hips down and back until the thighs are about level, then stand.',
      setup: 'Face the phone, feet shoulder-width, toes a little out, arms in front. Sit down and back until the thighs are near parallel, knees tracking over the toes, then drive up to standing.',
      why: 'Facing the phone both knees are seen: depth from the knee angle, and the knees caving toward each other as the gap between them shrinking.',
      progress: { metric: KNEE, start: 'calibrated', target: 95 },
      tempo: 'Down 2 s, up 1–2 s.', dosage: '3 × 12–15.', progression: 'Goblet squat; slower lowering; pause at the bottom.', regression: 'Squat to a box; shallower.',
      contraindications: 'Knee pain at depth; unable to keep the heels down.',
      faults: [ valgus(), { id: 'heels', label: 'Heels lifting', cue: 'Heels down', tip: 'Sit back into the hips; if the heels lift, raise them on a small plate for now.', severity: 2 }, { id: 'depth', label: 'Cutting depth', cue: 'Thighs to level', tip: 'Go as deep as the heels stay down and the back stays neutral.', severity: 1 } ],
      guide: { surface: 'Flat floor, flat shoes or bare feet.', stop: 'Sharp knee pain at depth.', cannotSee: 'The back rounding and the hips travelling back — side-view details.', regions: [{ name: 'Knees', points: [{ t: 'Track over the toes; stay apart at the bottom.', tracked: true }, { t: 'Thighs reach roughly parallel.', tracked: true }] }, { name: 'Feet', points: [{ t: 'Whole foot down; heels planted.', tracked: false }] }] },
      pose: { A: { legL: 10, legR: 10, armL: 10, armR: 10 }, B: { legL: 10, legR: 10, squat: .9, armL: 80, armR: 80, foreL: 88, foreR: 88 }, work: { thigh: 1, glute: .9, ham: .3 } },
    },
    {
      id: 'goblet_squat', name: 'Goblet squat', type: 'reps', view: 'side', tracking: 'form', level: 'beginner', equipment: ['dumbbell or kettlebell'],
      muscles: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['core', 'upper back'] },
      summary: 'Holding a weight at the chest, squat deep with the elbows inside the knees and the chest up.',
      setup: 'Stand side-on to the phone, a dumbbell held vertically at the chest. Sit down between the heels until the thighs are at or below parallel, keeping the chest up, then stand.',
      why: 'From the side the knee angle gives depth and the shoulder–hip line shows the trunk folding forward, which the weight at the chest tends to prevent.',
      progress: { metric: KNEE, start: 'calibrated', target: 90 },
      tempo: 'Down 3 s, up 1 s.', dosage: '3 × 8–12.', progression: 'Heavier; pause at the bottom.', regression: 'Bodyweight squat to a box.',
      contraindications: 'Knee pain at depth; lower back pain with the weight.',
      faults: [ lean(48), { id: 'heels', label: 'Heels lifting', cue: 'Heels down', tip: 'Spread the floor with the feet; heels stay planted.', severity: 2 }, { id: 'round', label: 'Lower back rounding at the bottom', cue: 'Stop before the tuck', tip: 'Squat only as deep as the lower back stays neutral.', severity: 2 } ],
      guide: { surface: 'Flat floor.', stop: 'Back or knee pain.', cannotSee: 'The knees caving — a front-view detail.', regions: [{ name: 'Depth', points: [{ t: 'Thighs at or below parallel.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Chest up; weight tight to the body.', tracked: true }] }] },
      pose: { A: { ...standing, uarm: 30, farm: 130 }, B: { ...standing, torso: 22, thigh: 95, shin: -40, uarm: 30, farm: 130 }, work: { thigh: 1, glute: .9, back: .4 } },
    },
    {
      id: 'sumo_squat', name: 'Sumo squat', type: 'reps', view: 'front', tracking: 'form', level: 'beginner', equipment: ['none', 'dumbbell (optional)'],
      muscles: { primary: ['adductors', 'gluteus maximus', 'quadriceps'], secondary: ['hamstrings'] },
      summary: 'Wide stance, toes turned out, sit straight down with the knees following the toes.',
      setup: 'Face the phone with the feet wide and toes turned out about 45°. Sit straight down, knees pushing out over the toes, until the thighs are near level, then stand.',
      why: 'Facing the phone the knee angle gives depth and the knees drifting inward — the main fault in a wide stance — is measured as the gap between them shrinking.',
      progress: { metric: KNEE, start: 'calibrated', target: 100 },
      tempo: 'Down 2 s, up 2 s.', dosage: '3 × 12.', progression: 'Hold a dumbbell between the legs.', regression: 'Narrower stance; shallower.',
      contraindications: 'Groin strain; hip pinching at depth.',
      faults: [ valgus(-14), { id: 'lean', label: 'Trunk tipping forward', cue: 'Torso upright', tip: 'A sumo squat is more upright than a normal squat; sit down, not back.', severity: 2 } ],
      guide: { surface: 'Flat floor.', stop: 'Groin or hip pain.', cannotSee: 'The trunk tipping forward — a side-view detail.', regions: [{ name: 'Knees', points: [{ t: 'Follow the toes outward all the way down.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Upright; weight hangs between the legs.', tracked: false }] }] },
      pose: { A: { legL: 22, legR: 22, armL: 15, armR: 15 }, B: { legL: 22, legR: 22, squat: .8, armL: 18, armR: 18 }, work: { thigh: 1, glute: .8 } },
    },
    {
      id: 'forward_lunge', name: 'Forward lunge', type: 'reps', view: 'side', tracking: 'form', level: 'intermediate', equipment: ['none', 'dumbbells (optional)'],
      muscles: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings', 'calves'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Step forward and lower until both knees are at about 90°, then push back to standing.',
      setup: 'Stand side-on to the phone, working leg nearest. Step that foot forward and lower straight down until the front thigh is level and the back knee hovers above the floor. Push off the front foot to return.',
      why: 'From the side the front knee angle gives depth, and the trunk pitching forward — the usual cheat — shows as the shoulder–hip line tilting.',
      progress: { metric: KNEE, start: 'calibrated', target: 95 },
      tempo: 'Down 2 s, up 1 s.', dosage: '3 × 8–10 each leg.', progression: 'Dumbbells; walking lunges.', regression: 'Split squat with no step; shorter step.',
      contraindications: 'Kneecap pain on the front leg; balance problems.',
      faults: [ lean(62), { id: 'kneefwd', label: 'Front knee shooting past the toes', cue: 'Shin near vertical', tip: 'Take a longer step so the shin stays close to upright; the knee should stay over the foot.', severity: 2 }, { id: 'short', label: 'Not lowering enough', cue: 'Back knee to the floor', tip: 'Drop the back knee toward the floor; the front thigh should reach level.', severity: 1 } ],
      guide: { surface: 'Enough floor for a long step.', stop: 'Kneecap pain.', cannotSee: 'The front knee drifting inward.', regions: [{ name: 'Front leg', points: [{ t: 'Thigh reaches level; shin near vertical.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Tall; lower straight down.', tracked: true }] }] },
      pose: { A: { ...standing, uarm: 8, farm: 8 }, B: { ...standing, thigh: 85, shin: -5, thighF: -30, shinF: -120, footF: -60, uarm: 8, farm: 8 }, work: { thigh: 1, glute: .9, calf: .3 } },
    },
    {
      id: 'reverse_lunge', name: 'Reverse lunge', type: 'reps', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['none', 'dumbbells (optional)'],
      muscles: { primary: ['gluteus maximus', 'quadriceps'], secondary: ['hamstrings'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Step back and lower until the back knee nearly touches, then drive up through the front heel.',
      setup: 'Stand side-on to the phone, working (front) leg nearest. Step the other foot back and lower until the front thigh is level, then push through the front heel to stand.',
      why: 'From the side the front knee angle closes every rep, so reps are counted. The trunk lean is smaller than in a forward lunge and is listed rather than judged.',
      progress: { metric: KNEE, start: 'calibrated', target: 95 },
      tempo: 'Down 2 s, up 1 s.', dosage: '3 × 10 each leg.', progression: 'Dumbbells; deficit from a low step.', regression: 'Hand on a support; shallower.',
      contraindications: 'Kneecap pain on the front leg.',
      faults: [ { id: 'lean', label: 'Trunk tipping forward', cue: 'Chest up', tip: 'Lower straight down; the back knee travels to the floor, the chest stays up.', severity: 2 }, { id: 'push', label: 'Pushing off the back foot', cue: 'Front heel drives', tip: 'The back foot is a kickstand; the front leg does the work.', severity: 2 } ],
      guide: { surface: 'Enough floor behind you.', stop: 'Kneecap pain.', cannotSee: 'Which leg is doing the pushing.', regions: [{ name: 'Front leg', points: [{ t: 'Thigh reaches level; heel stays down.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Tall.', tracked: false }] }] },
      pose: { A: { ...standing, uarm: 8, farm: 8 }, B: { ...standing, thigh: 85, shin: -5, thighF: -30, shinF: -120, footF: -60, uarm: 8, farm: 8 }, work: { glute: 1, thigh: .9 } },
    },
    {
      id: 'walking_lunge', name: 'Walking lunge', type: 'reps', view: 'side', tracking: 'none', level: 'intermediate', equipment: ['none', 'dumbbells (optional)'],
      muscles: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings', 'core'] },
      summary: 'Lunge forward and, instead of stepping back, bring the rear foot through into the next lunge.',
      setup: 'Start at one end of the room. Lunge forward, then step the back foot through into the next lunge. Keep going for the distance.',
      why: 'Walking takes you out of frame within a few steps. Logged by hand.',
      tempo: 'Controlled; 2 s per lunge.', dosage: '3 × 10 steps each leg.', progression: 'Dumbbells.', regression: 'Static forward lunges.',
      contraindications: 'Kneecap pain; balance problems.',
      faults: [ { id: 'lean', label: 'Trunk tipping forward', cue: 'Chest up', tip: 'Lower straight down each step.', severity: 2 }, { id: 'wobble', label: 'Wobbling side to side', cue: 'Feet on two rails', tip: 'Keep the feet hip-width apart, not on a tightrope.', severity: 1 } ],
      guide: { surface: 'A clear walkway.', stop: 'Kneecap pain.', cannotSee: 'You — the exercise walks out of frame.', regions: [{ name: 'Front leg', points: [{ t: 'Thigh to level each step.', tracked: false }] }, { name: 'Trunk', points: [{ t: 'Tall, steady.', tracked: false }] }] },
      pose: { A: { ...standing, thigh: 85, shin: -5, thighF: -30, shinF: -120, footF: -60, uarm: 8, farm: 8 }, B: { ...standing, thigh: -30, shin: -120, foot: -60, thighF: 85, shinF: -5, uarm: 8, farm: 8 }, work: { thigh: 1, glute: .9 } },
    },
    {
      id: 'lateral_lunge', name: 'Lateral lunge', type: 'reps', view: 'front', tracking: 'reps', level: 'intermediate', equipment: ['none', 'dumbbell (optional)'],
      muscles: { primary: ['adductors', 'gluteus maximus', 'quadriceps'], secondary: ['hamstrings'] }, sided: { limb: 'leg', by: 'pick' },
      summary: 'Step wide to one side and sit into that hip, the other leg straight, then push back.',
      setup: 'Face the phone, feet together. Step wide to the working side and sit the hips back over that foot, the other leg straight, then push back to the start.',
      why: 'Facing the phone the knees move far apart on every step, so reps are counted; where the weight sits is listed rather than judged.',
      progress: { metric: KNEES_APART, start: 'calibrated', target: 55, targetIsDelta: true },
      tempo: 'Out 2 s, back 1 s.', dosage: '3 × 8 each side.', progression: 'Hold a dumbbell at the chest.', regression: 'Smaller step.',
      contraindications: 'Groin strain; knee pain on the bent side.',
      faults: [ { id: 'knee', label: 'Bent knee caving inward', cue: 'Knee over the foot', tip: 'Sit back into the hip so the knee stays over the middle of the foot.', severity: 3 }, { id: 'toes', label: 'Toes turning out', cue: 'Toes forward', tip: 'Both feet point at the phone; the stretch is in the straight leg\'s inner thigh.', severity: 1 } ],
      guide: { surface: 'Room to step wide.', stop: 'Groin or knee pain.', cannotSee: 'The hips sitting back.', regions: [{ name: 'Bent leg', points: [{ t: 'Knee over the foot; hips sit back.', tracked: false }, { t: 'Feet wide apart at the bottom.', tracked: true }] }, { name: 'Straight leg', points: [{ t: 'Fully straight, foot flat.', tracked: false }] }] },
      pose: { A: { legL: 4, legR: 4, armL: 10, armR: 10 }, B: { legL: 8, shinL: 60, legR: 48, shinR: 48, squat: .25, armL: 60, armR: 60, foreL: 100, foreR: 100 }, work: { thigh: .8, glute: .8 } },
    },
    {
      id: 'rdl', name: 'Romanian deadlift', type: 'reps', view: 'side', tracking: 'form', level: 'intermediate', equipment: ['dumbbells or barbell'],
      muscles: { primary: ['hamstrings', 'gluteus maximus'], secondary: ['spinal erectors', 'grip'] },
      summary: 'Weights in hand, hinge at the hips with soft knees until the hamstrings pull, then stand tall.',
      setup: 'Stand side-on to the phone, weights in front of the thighs, knees soft. Push the hips back and let the weights slide down the legs, back flat, until the hamstrings pull. Drive the hips forward to stand.',
      why: 'From the side the shoulder–hip line hinges toward horizontal each rep, and the knees bending to turn it into a squat is caught by the knee angle.',
      progress: { metric: TRUNK, start: 'calibrated', target: 30 },
      tempo: 'Down 3 s, up 1–2 s.', dosage: '3 × 8–10.', progression: 'Heavier; single leg.', regression: 'Bodyweight hip hinge with a dowel on the back.',
      contraindications: 'Lower back pain; hamstring strain.',
      faults: [ kneesBend(140), { id: 'round', label: 'Back rounding', cue: 'Flat back', tip: 'Stop the descent when the back starts to round; chest proud, chin neutral.', severity: 3 }, { id: 'drift', label: 'Weights drifting away from the legs', cue: 'Weights on the legs', tip: 'Drag the weights down the thighs; away from the body loads the lower back.', severity: 2 } ],
      guide: { surface: 'Flat floor.', stop: 'Lower back pain.', cannotSee: 'The back rounding under a shirt.', regions: [{ name: 'Hips', points: [{ t: 'Travel back; trunk hinges toward level.', tracked: true }] }, { name: 'Knees', points: [{ t: 'Softly bent and still.', tracked: true }] }, { name: 'Back', points: [{ t: 'Flat throughout.', tracked: false }] }] },
      pose: { A: { ...standing, uarm: 5, farm: 5 }, B: { ...standing, torso: 70, thigh: -18, shin: 12, uarm: 95, farm: 95 }, work: { ham: 1, glute: 1, back: .5 } },
    },
    {
      id: 'single_leg_rdl', name: 'Single-leg Romanian deadlift', type: 'reps', view: 'side', tracking: 'reps', level: 'advanced', equipment: ['none', 'dumbbell (optional)'],
      muscles: { primary: ['hamstrings', 'gluteus maximus', 'gluteus medius'], secondary: ['core', 'ankle stabilisers'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Balancing on one leg, hinge forward as the other leg lifts behind, then return.',
      setup: 'Stand side-on to the phone on the working leg, knee soft. Hinge at the hip, reaching the free leg straight back and the hands toward the floor, until the body is near level. Return to standing.',
      why: 'From the side the trunk hinges toward horizontal every rep, so reps are counted. Hip rotation — the main fault — is a front-view detail.',
      progress: { metric: TRUNK, start: 'calibrated', target: 30 },
      tempo: 'Down 3 s, up 2 s.', dosage: '3 × 8 each leg.', progression: 'Hold a weight; slow the lowering.', regression: 'Fingertips on a wall; smaller hinge.',
      contraindications: 'Balance problems without support; hamstring strain.',
      faults: [ { id: 'open', label: 'Hip opening to the side', cue: 'Hips square', tip: 'Point the free toes at the floor so the pelvis stays level.', severity: 3 }, { id: 'round', label: 'Back rounding', cue: 'Long spine', tip: 'Reach the head forward and the heel back; stop before the back rounds.', severity: 2 } ],
      guide: { surface: 'Flat floor; a wall in reach.', stop: 'Back pain.', cannotSee: 'The hip opening.', regions: [{ name: 'Trunk', points: [{ t: 'Hinges toward level; back flat.', tracked: true }] }, { name: 'Free leg', points: [{ t: 'Reaches back in line with the trunk; toes down.', tracked: false }] }] },
      pose: { A: { ...standing, uarm: 5, farm: 5 }, B: { face: 'right', torso: 75, thigh: -10, shin: 8, thighF: -165, shinF: -165, footF: -20, uarm: 100, farm: 100 }, work: { ham: 1, glute: 1, back: .4 } },
    },
    {
      id: 'deadlift_db', name: 'Dumbbell deadlift', type: 'reps', view: 'side', tracking: 'form', level: 'intermediate', equipment: ['dumbbells or kettlebell'],
      muscles: { primary: ['gluteus maximus', 'hamstrings', 'quadriceps'], secondary: ['spinal erectors', 'grip', 'core'] },
      summary: 'Weights on the floor beside the feet; hinge and bend to grip them, then stand tall by driving the floor away.',
      setup: 'Stand side-on to the phone, weights beside the feet. Push the hips back and bend the knees to reach the weights with a flat back, then stand by driving the legs and hips together. Lower the same way.',
      why: 'From the side the trunk hinges and returns each rep, and the back folding further than the hips — the sign of a rounded pull — shows as the trunk angle dropping too far.',
      progress: { metric: TRUNK, start: 'calibrated', target: 40 },
      tempo: 'Down 2 s, up 1 s.', dosage: '3 × 6–8.', progression: 'Heavier; barbell.', regression: 'Weights on a low step; kettlebell between the feet.',
      contraindications: 'Lower back pain; unable to keep a flat back at the bottom.',
      faults: [ lean(22), { id: 'round', label: 'Back rounding', cue: 'Flat back', tip: 'Brace, chest proud, and lift the weights from a higher surface if the back rounds.', severity: 3 }, { id: 'hips', label: 'Hips shooting up first', cue: 'Hips and chest together', tip: 'The shoulders and hips rise at the same rate; if the hips lead, the back finishes the lift.', severity: 2 } ],
      guide: { surface: 'Flat, non-slip floor.', stop: 'Lower back pain.', cannotSee: 'The back rounding under a shirt.', regions: [{ name: 'Trunk', points: [{ t: 'Hinges with a flat back; stands fully tall.', tracked: true }] }, { name: 'Legs', points: [{ t: 'Knees bend enough to reach the weights; heels down.', tracked: false }] }] },
      pose: { A: { ...standing, uarm: 5, farm: 5 }, B: { ...standing, torso: 55, thigh: 55, shin: -25, uarm: 90, farm: 90 }, work: { glute: 1, ham: .9, thigh: .7, back: .6 } },
    },
    {
      id: 'good_morning', name: 'Good morning', type: 'reps', view: 'side', tracking: 'form', level: 'intermediate', equipment: ['none', 'band or light bar'],
      muscles: { primary: ['hamstrings', 'gluteus maximus', 'spinal erectors'], secondary: [] },
      summary: 'Hands behind the head, hinge at the hips with a flat back until the trunk is near level, then stand.',
      setup: 'Stand side-on to the phone, hands behind the head, knees soft. Push the hips back and bow forward with a flat back until the trunk is near level, then squeeze the glutes to stand.',
      why: 'From the side the trunk angle gives the hinge, and the knees bending to cheat is caught by the knee angle.',
      progress: { metric: TRUNK, start: 'calibrated', target: 35 },
      tempo: 'Down 3 s, up 2 s.', dosage: '3 × 10.', progression: 'Band around the neck and under the feet; light bar.', regression: 'Smaller hinge.',
      contraindications: 'Lower back pain.',
      faults: [ kneesBend(145), { id: 'round', label: 'Back rounding', cue: 'Flat back', tip: 'Stop before the back rounds; the range grows as the hamstrings loosen.', severity: 3 } ],
      guide: { surface: 'Flat floor.', stop: 'Lower back pain.', cannotSee: 'The back rounding.', regions: [{ name: 'Hips', points: [{ t: 'Travel back; trunk near level.', tracked: true }] }, { name: 'Knees', points: [{ t: 'Softly bent and still.', tracked: true }] }] },
      pose: { A: { ...standing, uarm: 150, farm: 60 }, B: { ...standing, torso: 70, thigh: -15, shin: 10, uarm: 160, farm: 60 }, work: { ham: 1, glute: .9, back: .8 } },
    },
    {
      id: 'bulgarian_split_squat', name: 'Bulgarian split squat', type: 'reps', view: 'side', tracking: 'reps', level: 'advanced', equipment: ['bench or chair', 'dumbbells (optional)'],
      muscles: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings', 'adductors'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Rear foot on a bench behind you, lower the front thigh to level and drive back up.',
      setup: 'Stand a long step in front of a bench, side-on to the phone, working leg nearest and the other foot resting on the bench. Lower straight down until the front thigh is level, then push back up.',
      why: 'From the side the front knee angle closes and opens each rep, so reps are counted.',
      progress: { metric: KNEE, start: 'calibrated', target: 95 },
      tempo: 'Down 2–3 s, up 1 s.', dosage: '3 × 8 each leg.', progression: 'Dumbbells; slower lowering.', regression: 'Split squat with the back foot on the floor.',
      contraindications: 'Kneecap pain; balance problems.',
      faults: [ { id: 'lean', label: 'Trunk folding forward', cue: 'Chest up', tip: 'A slight forward lean is fine; folding shifts the work to the back.', severity: 2 }, { id: 'kneein', label: 'Front knee caving inward', cue: 'Knee over the foot', tip: 'Push the knee out over the little toe.', severity: 3 } ],
      guide: { surface: 'A stable bench that will not slide.', stop: 'Kneecap pain.', cannotSee: 'The front knee caving.', regions: [{ name: 'Front leg', points: [{ t: 'Thigh reaches level; heel down.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Tall or slightly forward.', tracked: false }] }] },
      pose: { A: { ...standing, thigh: 20, shin: 0, thighF: -35, shinF: -120, footF: -60, uarm: 8, farm: 8 }, B: { ...standing, torso: 10, thigh: 85, shin: -5, thighF: -40, shinF: -130, footF: -60, uarm: 8, farm: 8 }, work: { thigh: 1, glute: .9 } },
    },
    {
      id: 'curtsy_lunge', name: 'Curtsy lunge', type: 'reps', view: 'front', tracking: 'none', level: 'intermediate', equipment: ['none'],
      muscles: { primary: ['gluteus medius', 'gluteus maximus', 'quadriceps'], secondary: ['adductors'] }, sided: { limb: 'leg', by: 'pick' },
      summary: 'Step one leg diagonally behind the other and lower, as if curtsying, then return.',
      setup: 'Face the phone. Step the free leg back and across behind the standing leg, lower until the front thigh is near level, then push back up.',
      why: 'The legs cross in front of each other from the front and the step goes away from a side phone. Logged by hand.',
      tempo: 'Down 2 s, up 1 s.', dosage: '3 × 10 each side.', progression: 'Dumbbell at the chest.', regression: 'Shorter step; hand on a support.',
      contraindications: 'Knee pain with the twist.',
      faults: [ { id: 'knee', label: 'Front knee caving', cue: 'Knee over the foot', tip: 'The front knee stays over the front foot even as the other leg crosses behind.', severity: 3 }, { id: 'hips', label: 'Hips turning', cue: 'Hips to the phone', tip: 'Only the leg crosses; the pelvis keeps facing forward.', severity: 2 } ],
      guide: { surface: 'Flat floor.', stop: 'Knee pain.', cannotSee: 'Almost everything — the legs cross.', regions: [{ name: 'Front leg', points: [{ t: 'Knee stays over the foot.', tracked: false }] }, { name: 'Hips', points: [{ t: 'Face forward.', tracked: false }] }] },
      pose: { A: { legL: 4, legR: 4, armL: 10, armR: 10 }, B: { legL: 4, shinL: 0, legR: -22, shinR: -10, squat: .35, armL: 60, armR: 60, foreL: 100, foreR: 100 }, work: { glute: 1, thigh: .7 } },
    },
    {
      id: 'glute_kickback', name: 'Glute kickback (quadruped)', type: 'reps', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['none', 'band or ankle weight (optional)'],
      muscles: { primary: ['gluteus maximus'], secondary: ['hamstrings', 'core'] }, sided: { limb: 'leg', by: 'camera' }, band: true,
      summary: 'On hands and knees, drive one heel up and back until the thigh is level with the back, then lower.',
      setup: 'Hands under the shoulders, knees under the hips, side-on to the phone at knee height, working leg nearest. Keeping the knee bent, push the heel toward the ceiling until the thigh is in line with the back. Lower without resting the knee.',
      why: 'From the side the working thigh swings from hanging to level each rep, so reps are counted. The back arching to lift higher is listed, not judged.',
      camera: { height: 'knee', distance: '2 m', posture: 'kneeling' },
      progress: { metric: { kind: 'vertical', pts: ['HIP', 'KNEE'] }, start: 'calibrated', target: 80 },
      tempo: 'Up 1 s, squeeze 1 s, down 2 s.', dosage: '3 × 12 each leg.', progression: 'Band around the foot; ankle weight.', regression: 'Smaller lift.',
      contraindications: 'Lower back pain on the lift; wrist pain.',
      faults: [ { id: 'arch', label: 'Lower back arching', cue: 'Thigh to level, no higher', tip: 'Higher than the back means the spine is lifting, not the glute.', severity: 2 }, { id: 'shift', label: 'Weight shifting to one side', cue: 'Hips square', tip: 'Keep the weight even over both hands and the resting knee.', severity: 1 } ],
      guide: { surface: 'A mat under the knees.', stop: 'Lower back or wrist pain.', cannotSee: 'The hips twisting.', regions: [{ name: 'Working leg', points: [{ t: 'Thigh lifts to level with the back; knee bent.', tracked: true }] }, { name: 'Back', points: [{ t: 'Flat and still.', tracked: false }] }] },
      pose: { A: { ...quadruped }, B: { ...quadruped, thigh: 88, shin: 0, foot: -60, thighF: 0, shinF: -90 }, work: { glute: 1, ham: .5 } },
    },
    {
      id: 'wall_sit', name: 'Wall sit', type: 'hold', view: 'side', tracking: 'form', level: 'beginner', equipment: ['wall'],
      muscles: { primary: ['quadriceps'], secondary: ['gluteus maximus', 'calves'] },
      summary: 'Back against a wall, slide down until the thighs are level and hold.',
      setup: 'Stand with the back flat on a wall, side-on to the phone. Walk the feet out and slide down until the knees are at 90° with the shins vertical. Hold.',
      why: 'From the side the knee angle tells whether you are actually at 90°; creeping up to rest the thighs is caught directly.',
      targets: [20, 30, 45, 60, 90], defaultTarget: 30,
      hold: { conditions: [{ metric: KNEE, min: 75, max: 110 }] },
      tempo: 'Still; breathe.', dosage: '3 × 30–60 s.', progression: 'Hold a weight; single leg.', regression: 'Higher position (knees at 120°).',
      contraindications: 'Kneecap pain.',
      faults: [ { id: 'creep', label: 'Creeping up the wall', cue: 'Thighs to level', tip: 'Slide back down until the knees are at a right angle.', severity: 2, metric: KNEE, op: '>', threshold: 110, phase: 'hold', persist: 800, cooldown: 6000 }, { id: 'knees', label: 'Knees past the toes', cue: 'Shins vertical', tip: 'Walk the feet further from the wall so the shins stand straight.', severity: 2 } ],
      guide: { surface: 'A smooth wall.', stop: 'Kneecap pain.', cannotSee: 'The knees drifting inward.', regions: [{ name: 'Knees', points: [{ t: 'At a right angle, shins vertical.', tracked: true }] }, { name: 'Back', points: [{ t: 'Flat on the wall.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 90, shin: 0, uarm: 8, farm: 8 }, B: { face: 'right', torso: 0, thigh: 90, shin: 0, uarm: 8, farm: 8 }, work: { thigh: 1, glute: .4 }, wall: 'behind' },
    },
    {
      id: 'jump_squat', name: 'Jump squat', type: 'reps', view: 'front', tracking: 'reps', level: 'advanced', equipment: ['none'],
      muscles: { primary: ['quadriceps', 'gluteus maximus', 'calves'], secondary: ['hamstrings', 'core'] },
      summary: 'Squat down and jump up, landing softly back into the squat.',
      setup: 'Face the phone, feet shoulder-width. Squat to about a quarter depth, jump as high as you can, and land quietly with the knees bending to absorb it.',
      why: 'Facing the phone the knee angle dips before each jump, so reps are counted. Landing mechanics happen too fast to judge reliably.',
      progress: { metric: KNEE, start: 'calibrated', target: 120 }, minMs: 500,
      tempo: 'Explosive up, soft landing.', dosage: '3 × 8.', progression: 'Deeper squat; continuous reps.', regression: 'Small hops; squat with a heel raise.',
      contraindications: 'Knee or ankle injury; anyone told to avoid impact.',
      faults: [ { id: 'stiff', label: 'Landing with stiff legs', cue: 'Land soft', tip: 'Bend the knees and hips on landing so it is quiet.', severity: 3 }, { id: 'valgus', label: 'Knees caving on landing', cue: 'Knees out', tip: 'Land with the knees over the toes.', severity: 3 } ],
      guide: { surface: 'A floor with some give; not concrete.', stop: 'Knee or ankle pain.', cannotSee: 'Landing mechanics — too fast.', regions: [{ name: 'Knees', points: [{ t: 'Dip into a quarter squat before every jump.', tracked: true }, { t: 'Bend on the landing; track over the toes.', tracked: false }] }, { name: 'Feet', points: [{ t: 'Land quietly, whole foot.', tracked: false }] }] },
      pose: { A: { legL: 8, legR: 8, squat: .5, armL: 40, armR: 40 }, B: { legL: 4, legR: 4, armL: 170, armR: 170 }, work: { thigh: 1, glute: .9, calf: .8 } },
    },
    {
      id: 'box_jump', name: 'Box jump', type: 'reps', view: 'side', tracking: 'none', level: 'advanced', equipment: ['sturdy box'],
      muscles: { primary: ['quadriceps', 'gluteus maximus', 'calves'], secondary: ['hamstrings'] },
      summary: 'Jump onto a box with both feet and land softly in a quarter squat; step down.',
      setup: 'Stand a short distance from a stable box. Swing the arms, jump and land with the whole foot on the box, knees soft. Stand tall, then step down.',
      why: 'The person changes height and position between the floor and the box, which confuses the calibrated counter. Logged by hand.',
      tempo: 'Explosive; step down.', dosage: '3 × 5.', progression: 'Higher box.', regression: 'Lower box; step-ups.',
      contraindications: 'Knee, ankle or Achilles injury; anyone told to avoid impact.',
      faults: [ { id: 'deep', label: 'Landing in a deep squat', cue: 'Land tall', tip: 'A deep landing means the box is too high; the hips should land above the knees.', severity: 2 }, { id: 'jumpdown', label: 'Jumping down', cue: 'Step down', tip: 'The jump down loads the tendons more than the jump up. Step.', severity: 2 } ],
      guide: { surface: 'A box that cannot tip.', stop: 'Knee or Achilles pain.', cannotSee: 'The landing.', regions: [{ name: 'Landing', points: [{ t: 'Whole foot on the box; knees soft; hips above the knees.', tracked: false }] }] },
      pose: { A: { ...standing, torso: 20, thigh: 50, shin: -20, uarm: -40, farm: -40 }, B: { ...standing, torso: 5, thigh: 30, shin: -10, uarm: 60, farm: 60 }, work: { thigh: 1, glute: 1, calf: .8 } },
    },
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
