/* Knee — catalogue moves. Data only; see coach/catalog.js for the fields and docs/EXERCISE-LIBRARY.md.
   Tracking is stated per move: form = counted and judged, reps = counted only, none = guide + hand-logged. */
(function (root) {
  'use strict';
  const C = (typeof module !== 'undefined' && module.exports) ? require('../catalog.js') : root.FyzioCatalog;
  const KNEE = { kind: 'angle', pts: ['HIP', 'KNEE', 'ANK'] };
  const TRUNK = { kind: 'tilt', pts: ['SH', 'HIP'] };
  const KNEES_APART = { kind: 'dist', pts: ['KNEE', 'oKNEE'] };
  const lean = (id, threshold, minP) => ({ id: id || 'lean', label: 'Leaning the trunk', cue: 'Stay tall', tip: 'The trunk tipping forward shifts the work to the back and hips. Chest up, look ahead.', severity: 2, metric: TRUNK, op: '<', threshold, minP: minP == null ? 0.25 : minP });

  C.defineCatalog({
    region: 'knee', group: 'Knee', order: 1100,
    camera: { height: 'hip', distance: '2.5 m', posture: 'standing' },
    sources: [
      { name: 'E3 Rehab — Exercises for knee pain', url: 'https://e3rehab.com/exercises-for-knee-pain/' },
      { name: 'Elevate Rehabilitation — what a physiotherapist prescribes for the knee', url: 'https://www.elevaterehabilitation.com/blog/knee-strengthening-exercises-what-a-physiotherapist-actually-prescribes' },
      { name: 'Rehab Hero — terminal knee extension', url: 'https://www.rehabhero.ca/exercise/terminal-knee-extension' },
    ],
  }, [
    {
      id: 'quad_set', name: 'Quad set', type: 'hold', view: 'side', tracking: 'none', level: 'beginner', equipment: ['none'],
      muscles: { primary: ['quadriceps'], secondary: [] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Tighten the thigh and press the back of the knee down. The first exercise after most knee surgery.',
      setup: 'Sit or lie with the leg straight, side-on to the phone at floor level. A rolled towel under the knee is fine. Tighten the front of the thigh so the kneecap draws up, hold, relax.',
      why: 'Almost nothing moves — the kneecap glides a centimetre. A camera cannot judge the squeeze, so this one is logged by hand.',
      camera: { height: 'floor', distance: '2 m', posture: 'lying' }, targets: [5, 8, 10], defaultTarget: 5,
      tempo: 'Squeeze 5 s, relax 3 s.', dosage: '10 × 5 s, several times a day.', progression: 'Straight leg raise once the thigh can lock the knee.', regression: 'Shorter squeezes, or with the knee slightly bent over a towel.',
      contraindications: 'Sharp pain in the joint, or a knee that will not straighten without swelling increasing.',
      faults: [
        { id: 'bend', label: 'Knee bending instead of pressing down', cue: 'Press the knee down', tip: 'The back of the knee should flatten toward the floor. If the heel lifts, the hip is doing the work.', severity: 2 },
        { id: 'breath', label: 'Holding the breath', cue: 'Keep breathing', tip: 'Count out loud through the squeeze so the breath cannot stop.', severity: 1 },
      ],
      guide: { surface: 'Firm floor or mat, or a bed if getting down is hard.', stop: 'Sharp pain inside the joint, or swelling that grows during the session.', cannotSee: 'The squeeze itself — the phone sees a still leg. It confirms position only.',
        regions: [{ name: 'Leg', points: [{ t: 'Leg straight, toes pointing up, heel resting on the floor.', tracked: false }, { t: 'Kneecap draws up toward the hip as the thigh tightens.', tracked: false }] }, { name: 'Trunk', points: [{ t: 'Sit tall or lie flat; no bracing with the arms.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: -90, thigh: 90, shin: 90, foot: 85, uarm: 90, farm: 90 }, B: { face: 'right', torso: -90, thigh: 90, shin: 90, foot: 92, uarm: 90, farm: 90 }, work: { thigh: 1 } },
    },
    {
      id: 'slr', name: 'Straight leg raise', type: 'reps', view: 'side', tracking: 'form', level: 'beginner', equipment: ['none', 'ankle weight (optional)'],
      muscles: { primary: ['quadriceps', 'hip flexors'], secondary: ['abdominals'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Lying on your back, lock the knee straight and lift the whole leg to the height of the other knee.',
      setup: 'Lie on your back, side-on to the phone at floor level, about 2 m away, working leg nearest the phone. Other knee bent, foot flat. Lock the working knee, lift the leg until it is level with the bent knee, pause, lower slowly.',
      why: 'From the side the leg is one line: its angle from the floor gives the lift, and the hip–knee–ankle angle shows whether the knee stays locked — the fault almost everyone makes.',
      camera: { height: 'floor', distance: '2 m', posture: 'lying' },
      progress: { metric: { kind: 'vertical', pts: ['HIP', 'KNEE'] }, start: 'calibrated', target: 35, targetIsDelta: true },
      tempo: 'Lift 2 s, hold 2 s, lower 3 s.', dosage: '2–3 × 10 each leg.', progression: 'Add a light ankle weight; pause longer at the top.', regression: 'Lift lower, or start with quad sets.',
      contraindications: 'Hip flexor pain or a lower back that arches and hurts on the lift.',
      faults: [
        { id: 'kneebend', label: 'Knee bending on the way up', cue: 'Lock the knee', tip: 'If the knee bends even a little, the hip flexors take over and the quad does nothing. Tighten the thigh before the leg leaves the floor.', severity: 3, metric: KNEE, op: '<', threshold: 165, minP: 0.15, persist: 300 },
        { id: 'arch', label: 'Lower back arching', cue: 'Back flat', tip: 'Press the lower back gently toward the floor; keeping the other knee bent makes this easier.', severity: 2 },
      ],
      guide: { surface: 'Firm floor or mat, not a bed.', stop: 'Pain in the front of the hip, or the back arching and hurting.', cannotSee: 'The back arching, and whether the foot is turning out.',
        regions: [{ name: 'Working leg', points: [{ t: 'Knee locked straight before it lifts and all the way through.', tracked: true }, { t: 'Lift only to the height of the other knee — higher adds nothing.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Lower back stays close to the floor; other knee bent.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: -90, thigh: 90, shin: 90, foot: 90, thighF: 45, shinF: 150, uarm: 90, farm: 90 }, B: { face: 'right', torso: -90, thigh: 125, shin: 125, foot: 125, thighF: 45, shinF: 150, uarm: 90, farm: 90 }, work: { thigh: 1, abs: .4 } },
    },
    {
      id: 'tke', name: 'Terminal knee extension (band)', type: 'reps', view: 'side', tracking: 'form', level: 'beginner', equipment: ['resistance band', 'anchor point'],
      muscles: { primary: ['quadriceps (VMO)'], secondary: ['gluteus maximus'] }, sided: { limb: 'leg', by: 'camera' }, band: 'yellow',
      summary: 'A band behind the knee pulls it forward; you press the knee back to fully straight.',
      setup: 'Loop a band around a solid anchor in front of you at knee height and around the back of the working knee. Step back until the band is taut with a soft knee, side-on to the phone. Straighten the knee fully against the band, hold a second, soften and repeat.',
      why: 'Side-on, the hip–knee–ankle angle reads the last few degrees of straightening directly, which is exactly the range this move is for.',
      progress: { metric: KNEE, start: 'calibrated', target: 178 },
      tempo: 'Straighten 1 s, hold 1 s, release 2 s.', dosage: '3 × 15.', progression: 'Heavier band; single-leg stance.', regression: 'Lighter band, or hands on a support.',
      contraindications: 'A knee that locks or gives way, or pain at the back of the knee under the band.',
      faults: [ lean('lean', 72), { id: 'hips', label: 'Hips pushing back', cue: 'Hips forward', tip: 'The band should straighten the knee, not fold you at the hip. Keep the hips over the feet.', severity: 2 } ],
      guide: { surface: 'Any firm floor; the anchor must not move.', stop: 'Pain behind the knee, or the knee not straightening at all.', cannotSee: 'Whether the kneecap is tracking straight.',
        regions: [{ name: 'Knee', points: [{ t: 'Straightens fully against the band each rep.', tracked: true }, { t: 'Kneecap points straight ahead, not inward.', tracked: false }] }, { name: 'Trunk', points: [{ t: 'Upright — the knee moves, the body does not.', tracked: true }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 12, shin: -12 }, B: { face: 'right', torso: 0, thigh: 0, shin: 0 }, work: { thigh: 1, glute: .3 }, wall: 'ahead', props: [{ kind: 'band', at: 'kn' }] },
    },
    {
      id: 'step_up', name: 'Step-up', type: 'reps', view: 'side', tracking: 'form', level: 'intermediate', equipment: ['step or stair'],
      muscles: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings', 'calves'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Step up onto a box with one leg and drive to standing tall on it, then lower with control.',
      setup: 'A step or box 15–25 cm high, side-on to the phone with the working leg nearest. Whole foot on the step. Push through that foot to stand fully on the step, tap the other foot up, then lower slowly to the floor.',
      why: 'The knee angle of the lead leg goes from bent to straight every rep, and a trunk that pitches forward to cheat shows up as the shoulder–hip line tilting.',
      progress: { metric: KNEE, start: 'calibrated', target: 175 },
      tempo: 'Up 1–2 s, down 3 s.', dosage: '3 × 8–12 each leg.', progression: 'Higher step; hold a weight; slow the lowering.', regression: 'Lower step, hand on a rail.',
      contraindications: 'Pain under the kneecap on the way down; poor balance without a rail.',
      faults: [ lean('lean', 65, 0.3), { id: 'push', label: 'Pushing off the back foot', cue: 'Lead leg does the work', tip: 'The floor foot should be almost weightless. If you bounce off it, the lead leg is not lifting you.', severity: 2 } ],
      guide: { surface: 'A stable step that cannot tip; a wall or rail within reach.', stop: 'Sharp kneecap pain, or the knee collapsing inward.', cannotSee: 'The knee drifting inward — that needs a front view.',
        regions: [{ name: 'Lead leg', points: [{ t: 'Whole foot on the step; knee finishes straight at the top.', tracked: true }, { t: 'Knee tracks over the middle toes, not inward.', tracked: false }] }, { name: 'Trunk', points: [{ t: 'Tall through the lift; a little forward lean is fine, folding is not.', tracked: true }] }] },
      pose: { A: { face: 'right', torso: 8, thigh: 80, shin: 0, thighF: 0, shinF: 0 }, B: { face: 'right', torso: 0, thigh: 0, shin: 0, thighF: 0, shinF: 0 }, work: { thigh: 1, glute: .8, calf: .4 }, anchor: 'an', props: [{ kind: 'box', at: 'an', w: 44, dy: 4 }] },
    },
    {
      id: 'mini_squat', name: 'Mini squat', type: 'reps', view: 'front', tracking: 'form', level: 'beginner', equipment: ['none', 'chair for support (optional)'],
      muscles: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings'] },
      summary: 'A shallow squat to about a third of the way down, knees tracking over the toes.',
      setup: 'Face the phone, feet hip-width, toes slightly out, hands on a chair back if needed. Bend the knees and sit the hips back a little, keeping the heels down, then stand tall.',
      why: 'Facing the phone shows both knees at once: the depth from each knee angle, and the classic fault — knees drifting toward each other — as the distance between them shrinking.',
      camera: { height: 'hip', distance: '2.5 m', posture: 'standing' },
      progress: { metric: KNEE, start: 'calibrated', target: 140 },
      tempo: 'Down 2 s, up 2 s.', dosage: '3 × 12.', progression: 'Deeper; hold a weight at the chest.', regression: 'Shallower, or hands on the chair.',
      contraindications: 'Pain under the kneecap at the bottom.',
      faults: [ { id: 'valgus', label: 'Knees caving inward', cue: 'Knees out', tip: 'Screw the feet into the floor so the knees track over the second toe. Caving loads the inside of the knee.', severity: 3, metric: KNEES_APART, rel: 'change', op: '<', threshold: -12, minP: 0.3, persist: 300 }, { id: 'heels', label: 'Heels lifting', cue: 'Heels down', tip: 'Sit the hips back rather than driving the knees forward; the weight belongs in the whole foot.', severity: 2 } ],
      guide: { surface: 'Firm floor, bare feet or flat shoes.', stop: 'Kneecap pain, or the knee collapsing inward.', cannotSee: 'How far the hips travel back — that is a side-view detail.',
        regions: [{ name: 'Knees', points: [{ t: 'Track over the toes, staying apart at the bottom.', tracked: true }, { t: 'Only a third of the way down — this is a mini squat.', tracked: true }] }, { name: 'Feet', points: [{ t: 'Heels stay down; weight through the whole foot.', tracked: false }] }] },
      pose: { A: { legL: 6, legR: 6, armL: 10, armR: 10 }, B: { legL: 6, legR: 6, squat: .45, armL: 30, armR: 30, foreL: 60, foreR: 60 }, work: { thigh: 1, glute: .7 } },
    },
    {
      id: 'sit_to_stand', name: 'Sit to stand', type: 'reps', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['chair'],
      muscles: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings', 'calves'] },
      summary: 'Stand up from a chair and sit back down without using the hands.',
      setup: 'A firm chair, side-on to the phone. Feet flat and slightly back, lean forward from the hips, stand fully tall, then lower slowly until you touch the seat.',
      why: 'Side-on the knee angle runs from about 90° to straight every rep, so each stand is counted. Whether the hands helped is not reliably visible, so form is listed rather than judged.',
      progress: { metric: KNEE, start: 'calibrated', target: 172 },
      tempo: 'Up 2 s, down 3 s.', dosage: '3 × 8–10.', progression: 'Lower chair; arms crossed; hold a weight.', regression: 'Higher seat, or a light push from the hands.',
      contraindications: 'Dizziness on standing.',
      faults: [ { id: 'hands', label: 'Pushing up with the hands', cue: 'No hands', tip: 'Cross the arms over the chest so the legs must do all the work.', severity: 2 }, { id: 'drop', label: 'Dropping into the seat', cue: 'Lower slowly', tip: 'The sit-down is half the exercise. Take three seconds and touch the seat lightly.', severity: 2 } ],
      guide: { surface: 'A stable chair against a wall so it cannot slide.', stop: 'Dizziness, or knee pain on the way down.', cannotSee: 'The hands pushing on the thighs or the chair.',
        regions: [{ name: 'Feet', points: [{ t: 'Flat, slightly behind the knees, hip-width apart.', tracked: false }] }, { name: 'Trunk', points: [{ t: 'Nose over toes to start the stand, then tall at the top.', tracked: true }] }] },
      pose: { A: { face: 'right', torso: 15, thigh: 90, shin: 0, uarm: 30, farm: 100 }, B: { face: 'right', torso: 0, thigh: 0, shin: 0, uarm: 30, farm: 100 }, work: { thigh: 1, glute: .8 }, props: [{ kind: 'box', at: 'hip', w: 34, dy: 2 }] },
    },
    {
      id: 'standing_ham_curl', name: 'Standing hamstring curl', type: 'reps', view: 'side', tracking: 'form', level: 'beginner', equipment: ['none', 'ankle weight or band (optional)'],
      muscles: { primary: ['hamstrings'], secondary: ['gluteus maximus', 'calves'] }, sided: { limb: 'leg', by: 'camera' }, band: true,
      summary: 'Standing tall, bend one knee to bring the heel toward the buttock, thigh staying still.',
      setup: 'Stand side-on to the phone, hands on a wall or chair in front, working leg nearest the phone. Keeping the thigh pointing straight down, bend the knee to lift the heel behind you, then lower with control.',
      why: 'From the side the knee angle gives the curl, and the thigh swinging forward — the way people cheat — shows as the hip–knee line leaving vertical.',
      progress: { metric: KNEE, start: 'calibrated', target: 90 },
      tempo: 'Up 2 s, down 3 s.', dosage: '3 × 12 each leg.', progression: 'Ankle weight or band around the ankles.', regression: 'Smaller bend, or lying on your front.',
      contraindications: 'Cramp or sharp pain at the back of the thigh.',
      faults: [ { id: 'swing', label: 'Thigh swinging forward', cue: 'Thigh still', tip: 'The hip should not move — only the knee bends. Squeeze the buttock to keep the thigh pointing down.', severity: 3, metric: { kind: 'tilt', pts: ['HIP', 'KNEE'] }, op: '<', threshold: 70, minP: 0.3, persist: 300 }, { id: 'arch', label: 'Arching the lower back', cue: 'Ribs down', tip: 'Brace the stomach lightly so the back does not sway as the heel rises.', severity: 2 } ],
      guide: { surface: 'Firm floor; something solid to hold in front.', stop: 'Hamstring cramp or a sharp pull.', cannotSee: 'The back arching, and the foot turning in or out.',
        regions: [{ name: 'Working leg', points: [{ t: 'Thigh vertical and still; only the knee bends.', tracked: true }, { t: 'Heel travels toward the buttock, not out to the side.', tracked: false }] }, { name: 'Trunk', points: [{ t: 'Tall, light hands on the support.', tracked: true }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 0, shin: 0, uarm: 60, farm: 60 }, B: { face: 'right', torso: 0, thigh: 0, shin: -90, uarm: 60, farm: 60 }, work: { ham: 1, glute: .4, calf: .3 }, wall: 'ahead' },
    },
    {
      id: 'seated_knee_ext', name: 'Seated knee extension', type: 'reps', view: 'side', tracking: 'form', level: 'beginner', equipment: ['chair', 'ankle weight (optional)'],
      muscles: { primary: ['quadriceps'], secondary: [] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Sitting, straighten one knee until the leg is level, hold, and lower.',
      setup: 'Sit tall on a chair, side-on to the phone, working leg nearest. Straighten the knee until the leg is horizontal, pause with the thigh tight, then lower slowly.',
      why: 'Side-on the knee angle runs from 90° to straight, and leaning back to help shows as the trunk line tilting away from upright.',
      camera: { height: 'hip', distance: '2 m', posture: 'sitting' },
      progress: { metric: KNEE, start: 'calibrated', target: 172 },
      tempo: 'Up 2 s, hold 2 s, down 3 s.', dosage: '3 × 10–15 each leg.', progression: 'Ankle weight; longer hold at the top.', regression: 'Part range, or stop short of straight if it clicks.',
      contraindications: 'Sharp pain under the kneecap near full straightening.',
      faults: [ { id: 'leanback', label: 'Leaning back to help', cue: 'Sit tall', tip: 'Leaning back lets the hip flexors join in. Keep the trunk upright and the thigh on the seat.', severity: 2, metric: TRUNK, op: '<', threshold: 68, minP: 0.3, persist: 300 }, { id: 'drop', label: 'Letting the leg drop', cue: 'Lower slowly', tip: 'The lowering builds the muscle. Three seconds down, every rep.', severity: 1 } ],
      guide: { surface: 'A chair high enough that the feet hang or just touch.', stop: 'Kneecap pain, or the knee locking with a clunk.', cannotSee: 'The thigh lifting off the seat.',
        regions: [{ name: 'Working leg', points: [{ t: 'Straightens fully with the thigh tight; toes pulled up.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Upright, hands resting on the seat edge, not gripping.', tracked: true }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 90, shin: 0, foot: 0, uarm: 20, farm: 40 }, B: { face: 'right', torso: 0, thigh: 90, shin: 90, foot: 90, shinF: 0, footF: 0, uarm: 20, farm: 40 }, work: { thigh: 1 }, props: [{ kind: 'box', at: 'hip', w: 34, dy: 2 }] },
    },
    {
      id: 'split_squat', name: 'Split squat', type: 'reps', view: 'side', tracking: 'reps', level: 'intermediate', equipment: ['none', 'dumbbells (optional)'],
      muscles: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings', 'hip flexors (rear leg)'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'A stationary lunge: one foot forward, one back, lower the rear knee toward the floor and stand.',
      setup: 'Take a long stride so the front foot is flat and the rear heel is up, front leg nearest the phone. Lower straight down until the rear knee is near the floor, then drive up through the front heel.',
      why: 'The front knee angle counts the reps cleanly from the side. The knee drifting inward — the fault that matters — needs a front view, so form is listed here rather than judged.',
      progress: { metric: KNEE, start: 'calibrated', target: 95 },
      tempo: 'Down 2 s, up 1 s.', dosage: '3 × 8–10 each leg.', progression: 'Hold dumbbells; rear foot on a step.', regression: 'Shorter stride, shallower, hand on a wall.',
      contraindications: 'Kneecap pain in the front leg, or hip flexor pain in the rear leg.',
      faults: [ { id: 'valgus', label: 'Front knee caving inward', cue: 'Knee over toes', tip: 'Point the knee where the toes point. If it falls inward, shorten the stride and go shallower.', severity: 3 }, { id: 'forward', label: 'Knee shooting forward', cue: 'Straight down', tip: 'Lower like an elevator, not a slide. The front shin stays near vertical.', severity: 2 } ],
      guide: { surface: 'Firm floor with grip.', stop: 'Kneecap pain, or losing balance.', cannotSee: 'The front knee drifting inward.',
        regions: [{ name: 'Front leg', points: [{ t: 'Foot flat, shin close to vertical at the bottom.', tracked: true }, { t: 'Knee over the middle of the foot.', tracked: false }] }, { name: 'Rear leg', points: [{ t: 'Heel up, knee lowers toward the floor without touching.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: 25, shin: -25, thighF: -20, shinF: -20 }, B: { face: 'right', torso: 5, thigh: 70, shin: -20, thighF: -35, shinF: 35 }, work: { thigh: 1, glute: .8, ham: .4 } },
    },
    {
      id: 'supine_ham_stretch', name: 'Hamstring stretch (lying)', type: 'hold', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['strap or towel'],
      muscles: { primary: ['hamstrings'], secondary: ['calves'] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'On your back, a strap around the foot, raise the straight leg until the back of the thigh pulls.',
      setup: 'Lie on your back, side-on to the phone at floor level, working leg nearest. Loop a strap or towel around the foot, keep the knee straight and draw the leg up toward vertical until you feel the stretch. Hold.',
      why: 'The leg angle from the floor shows how far up it is, so the timer only runs while the leg is actually held high.',
      camera: { height: 'floor', distance: '2 m', posture: 'lying' }, targets: [20, 30, 45, 60], defaultTarget: 30,
      hold: { conditions: [{ metric: { kind: 'vertical', pts: ['HIP', 'KNEE'] }, min: 135 }] },
      tempo: 'Ease in over 5 s, hold, ease out.', dosage: '3 × 30 s each leg.', progression: 'Take the leg higher; point the toes up.', regression: 'Bend the other knee; stop lower.',
      contraindications: 'Pins and needles down the leg, or back pain during the hold.',
      faults: [ { id: 'bend', label: 'Knee bending to cheat the stretch', cue: 'Knee straight', tip: 'A bent knee moves the stretch off the hamstring. Lower the leg until it can stay straight.', severity: 2 }, { id: 'hiplift', label: 'Hip lifting off the floor', cue: 'Hip down', tip: 'Keep the other leg and both hips on the floor; the stretch should be in the thigh, not the back.', severity: 2 } ],
      guide: { surface: 'Firm floor or mat.', stop: 'Nerve-like tingling, or pain in the lower back.', cannotSee: 'The knee bending slightly, and the toes pointing.',
        regions: [{ name: 'Working leg', points: [{ t: 'Knee straight, leg held toward vertical.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Hips and shoulders flat on the floor.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: -90, thigh: 125, shin: 125, foot: 125, thighF: 90, shinF: 90, uarm: 130, farm: 150 }, B: { face: 'right', torso: -90, thigh: 155, shin: 155, foot: 155, thighF: 90, shinF: 90, uarm: 150, farm: 165 }, work: { ham: 1, calf: .3 } },
    },
    {
      id: 'standing_quad_stretch', name: 'Quad stretch (standing)', type: 'hold', view: 'side', tracking: 'reps', level: 'beginner', equipment: ['wall or chair for balance'],
      muscles: { primary: ['quadriceps', 'hip flexors'], secondary: [] }, sided: { limb: 'leg', by: 'camera' },
      summary: 'Standing, hold one ankle behind you and draw the heel toward the buttock, knees together.',
      setup: 'Stand side-on to the phone, one hand on a wall. Bend the working knee, hold the ankle behind you, and gently pull the heel toward the buttock with the knee pointing down. Hold.',
      why: 'The knee angle from the side shows how far the heel has come up, so the timer runs only in the stretch position.',
      targets: [20, 30, 45, 60], defaultTarget: 30,
      hold: { conditions: [{ metric: KNEE, max: 60 }] },
      tempo: 'Ease in over 5 s, hold, release slowly.', dosage: '3 × 30 s each leg.', progression: 'Tuck the pelvis under to deepen; no wall.', regression: 'Hold the trouser leg or a strap; lie on your side.',
      contraindications: 'Kneecap pain in the bent knee, or cramp in the hamstring.',
      faults: [ { id: 'knee', label: 'Knee drifting forward or out', cue: 'Knee points down', tip: 'Keep the two knees side by side. The stretch comes from the hip extending, not the knee flaring.', severity: 2 }, { id: 'arch', label: 'Arching the back', cue: 'Tuck the pelvis', tip: 'Squeeze the buttock and tuck the tailbone under — that is where the stretch deepens.', severity: 2 } ],
      guide: { surface: 'Firm floor and something to hold.', stop: 'Kneecap pain or hamstring cramp.', cannotSee: 'The lower back arching.',
        regions: [{ name: 'Working leg', points: [{ t: 'Heel to buttock, knee pointing at the floor beside the other knee.', tracked: true }] }, { name: 'Trunk', points: [{ t: 'Tall, pelvis tucked, light hand on the wall.', tracked: false }] }] },
      pose: { A: { face: 'right', torso: 0, thigh: -8, shin: -150, uarm: -40, farm: -70, uarmF: 60, farmF: 60 }, B: { face: 'right', torso: 0, thigh: -14, shin: -165, uarm: -45, farm: -80, uarmF: 60, farmF: 60 }, work: { thigh: 1 }, wall: 'ahead' },
    },
    {
      id: 'step_down', name: 'Step-down (eccentric)', type: 'reps', view: 'front', tracking: 'form', level: 'intermediate', equipment: ['step or stair'],
      muscles: { primary: ['quadriceps', 'gluteus medius'], secondary: ['gluteus maximus'] }, sided: { limb: 'leg', by: 'pick' },
      summary: 'Standing on a step on one leg, lower the other heel slowly toward the floor and rise again.',
      setup: 'Stand on a step facing the phone, weight on the working leg, other foot hanging in front. Bend the standing knee to lower the free heel toward the floor, touch lightly, and press back up. Hips level throughout.',
      why: 'Facing the phone shows the standing knee angle for the count and, more usefully, the pelvis: the free-side hip dropping is the sign the outer hip muscles have let go.',
      camera: { height: 'hip', distance: '2.5 m', posture: 'standing' },
      progress: { metric: KNEE, start: 'calibrated', target: 130 },
      tempo: 'Down 3 s, up 1 s.', dosage: '3 × 8 each leg.', progression: 'Higher step; hold a weight.', regression: 'Lower step, fingertips on a wall.',
      contraindications: 'Kneecap pain on the way down.',
      faults: [ { id: 'hipdrop', label: 'Hip dropping on the free side', cue: 'Hips level', tip: 'Think of lifting the free hip as you lower. A dropping pelvis means the standing hip is not holding you.', severity: 3, metric: { kind: 'pelvis', pts: [] }, rel: 'change', op: '>', threshold: 6, minP: 0.25, persist: 350 }, { id: 'valgus', label: 'Knee caving inward', cue: 'Knee over toes', tip: 'Keep the standing knee over the middle of the foot as you lower.', severity: 3 } ],
      guide: { surface: 'A stable step; a wall within fingertip reach.', stop: 'Kneecap pain, or the knee collapsing inward.', cannotSee: 'How far the knee travels forward over the toes.',
        regions: [{ name: 'Standing leg', points: [{ t: 'Knee bends over the middle of the foot; heel stays down.', tracked: false }] }, { name: 'Pelvis', points: [{ t: 'Both hip bones stay level as you lower.', tracked: true }] }] },
      pose: { A: { legL: 0, legR: 0, armL: 12, armR: 12 }, B: { legR: 4, shinR: -4, squat: .4, legL: 14, shinL: 0, armL: 30, armR: 30 }, work: { thigh: 1, glute: .9 } },
    },
  ]);
})(typeof window !== 'undefined' ? window : globalThis);
